/**
 * This class is generated by jOOQ
 */
package com.cf.public_;


import com.cf.public_.tables.Qs;
import com.cf.public_.tables.Uni;
import com.cf.public_.tables.records.QsRecord;
import com.cf.public_.tables.records.UniRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UniRecord> UNI_PKEY = UniqueKeys0.UNI_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<QsRecord, UniRecord> QS__QS_ID_FKEY = ForeignKeys0.QS__QS_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<UniRecord> UNI_PKEY = createUniqueKey(Uni.UNI, "uni_pkey", Uni.UNI.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<QsRecord, UniRecord> QS__QS_ID_FKEY = createForeignKey(com.cf.public_.Keys.UNI_PKEY, Qs.QS, "qs__qs_id_fkey", Qs.QS.ID);
    }
}
