/**
 * This class is generated by jOOQ
 */
package com.cf.public_;


import com.cf.public_.tables.Qs;
import com.cf.public_.tables.Uni;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.qs</code>.
     */
    public static final Qs QS = com.cf.public_.tables.Qs.QS;

    /**
     * The table <code>public.uni</code>.
     */
    public static final Uni UNI = com.cf.public_.tables.Uni.UNI;
}
