/**
 * This class is generated by jOOQ
 */
package com.capitalfloat.jooq.public_;


import com.capitalfloat.jooq.public_.tables.Filings;
import com.capitalfloat.jooq.public_.tables.Tax;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.filings</code>.
     */
    public static final Filings FILINGS = com.capitalfloat.jooq.public_.tables.Filings.FILINGS;

    /**
     * The table <code>public.tax</code>.
     */
    public static final Tax TAX = com.capitalfloat.jooq.public_.tables.Tax.TAX;
}
