/**
 * This class is generated by jOOQ
 */
package com.capitalfloat.jooq.model;


import com.capitalfloat.jooq.model.tables.Author;
import com.capitalfloat.jooq.model.tables.Book;
import com.capitalfloat.jooq.model.tables.BookStore;
import com.capitalfloat.jooq.model.tables.BookToBookStore;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.capitalfloat.jooq.model.tables.Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public static final Book BOOK = com.capitalfloat.jooq.model.tables.Book.BOOK;

    /**
     * The table <code>library.book_store</code>.
     */
    public static final BookStore BOOK_STORE = com.capitalfloat.jooq.model.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>library.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = com.capitalfloat.jooq.model.tables.BookToBookStore.BOOK_TO_BOOK_STORE;
}
