/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog;


import com.cf.pg_catalog.tables.PgAggregate;
import com.cf.pg_catalog.tables.PgAm;
import com.cf.pg_catalog.tables.PgAmop;
import com.cf.pg_catalog.tables.PgAmproc;
import com.cf.pg_catalog.tables.PgAttrdef;
import com.cf.pg_catalog.tables.PgAttribute;
import com.cf.pg_catalog.tables.PgAuthMembers;
import com.cf.pg_catalog.tables.PgAvailableExtensionVersions;
import com.cf.pg_catalog.tables.PgAvailableExtensions;
import com.cf.pg_catalog.tables.PgCast;
import com.cf.pg_catalog.tables.PgClass;
import com.cf.pg_catalog.tables.PgCollation;
import com.cf.pg_catalog.tables.PgConstraint;
import com.cf.pg_catalog.tables.PgConversion;
import com.cf.pg_catalog.tables.PgCursors;
import com.cf.pg_catalog.tables.PgDatabase;
import com.cf.pg_catalog.tables.PgDbRoleSetting;
import com.cf.pg_catalog.tables.PgDefaultAcl;
import com.cf.pg_catalog.tables.PgDepend;
import com.cf.pg_catalog.tables.PgDescription;
import com.cf.pg_catalog.tables.PgEnum;
import com.cf.pg_catalog.tables.PgEventTrigger;
import com.cf.pg_catalog.tables.PgExtension;
import com.cf.pg_catalog.tables.PgForeignDataWrapper;
import com.cf.pg_catalog.tables.PgForeignServer;
import com.cf.pg_catalog.tables.PgForeignTable;
import com.cf.pg_catalog.tables.PgGroup;
import com.cf.pg_catalog.tables.PgIndex;
import com.cf.pg_catalog.tables.PgIndexes;
import com.cf.pg_catalog.tables.PgInherits;
import com.cf.pg_catalog.tables.PgLanguage;
import com.cf.pg_catalog.tables.PgLargeobjectMetadata;
import com.cf.pg_catalog.tables.PgLocks;
import com.cf.pg_catalog.tables.PgMatviews;
import com.cf.pg_catalog.tables.PgNamespace;
import com.cf.pg_catalog.tables.PgOpclass;
import com.cf.pg_catalog.tables.PgOperator;
import com.cf.pg_catalog.tables.PgOpfamily;
import com.cf.pg_catalog.tables.PgPltemplate;
import com.cf.pg_catalog.tables.PgPolicies;
import com.cf.pg_catalog.tables.PgPolicy;
import com.cf.pg_catalog.tables.PgPreparedStatements;
import com.cf.pg_catalog.tables.PgPreparedXacts;
import com.cf.pg_catalog.tables.PgProc;
import com.cf.pg_catalog.tables.PgRange;
import com.cf.pg_catalog.tables.PgReplicationOrigin;
import com.cf.pg_catalog.tables.PgReplicationSlots;
import com.cf.pg_catalog.tables.PgRewrite;
import com.cf.pg_catalog.tables.PgRoles;
import com.cf.pg_catalog.tables.PgRules;
import com.cf.pg_catalog.tables.PgSeclabel;
import com.cf.pg_catalog.tables.PgSeclabels;
import com.cf.pg_catalog.tables.PgSettings;
import com.cf.pg_catalog.tables.PgShdepend;
import com.cf.pg_catalog.tables.PgShdescription;
import com.cf.pg_catalog.tables.PgShseclabel;
import com.cf.pg_catalog.tables.PgStatActivity;
import com.cf.pg_catalog.tables.PgStatAllIndexes;
import com.cf.pg_catalog.tables.PgStatAllTables;
import com.cf.pg_catalog.tables.PgStatArchiver;
import com.cf.pg_catalog.tables.PgStatBgwriter;
import com.cf.pg_catalog.tables.PgStatDatabase;
import com.cf.pg_catalog.tables.PgStatDatabaseConflicts;
import com.cf.pg_catalog.tables.PgStatReplication;
import com.cf.pg_catalog.tables.PgStatSsl;
import com.cf.pg_catalog.tables.PgStatSysIndexes;
import com.cf.pg_catalog.tables.PgStatSysTables;
import com.cf.pg_catalog.tables.PgStatUserFunctions;
import com.cf.pg_catalog.tables.PgStatUserIndexes;
import com.cf.pg_catalog.tables.PgStatUserTables;
import com.cf.pg_catalog.tables.PgStatXactAllTables;
import com.cf.pg_catalog.tables.PgStatXactSysTables;
import com.cf.pg_catalog.tables.PgStatXactUserFunctions;
import com.cf.pg_catalog.tables.PgStatXactUserTables;
import com.cf.pg_catalog.tables.PgStatioAllIndexes;
import com.cf.pg_catalog.tables.PgStatioAllSequences;
import com.cf.pg_catalog.tables.PgStatioAllTables;
import com.cf.pg_catalog.tables.PgStatioSysIndexes;
import com.cf.pg_catalog.tables.PgStatioSysSequences;
import com.cf.pg_catalog.tables.PgStatioSysTables;
import com.cf.pg_catalog.tables.PgStatioUserIndexes;
import com.cf.pg_catalog.tables.PgStatioUserSequences;
import com.cf.pg_catalog.tables.PgStatioUserTables;
import com.cf.pg_catalog.tables.PgStats;
import com.cf.pg_catalog.tables.PgTables;
import com.cf.pg_catalog.tables.PgTablespace;
import com.cf.pg_catalog.tables.PgTimezoneAbbrevs;
import com.cf.pg_catalog.tables.PgTimezoneNames;
import com.cf.pg_catalog.tables.PgTransform;
import com.cf.pg_catalog.tables.PgTrigger;
import com.cf.pg_catalog.tables.PgTsConfig;
import com.cf.pg_catalog.tables.PgTsConfigMap;
import com.cf.pg_catalog.tables.PgTsDict;
import com.cf.pg_catalog.tables.PgTsParser;
import com.cf.pg_catalog.tables.PgTsTemplate;
import com.cf.pg_catalog.tables.PgType;
import com.cf.pg_catalog.tables.PgUser;
import com.cf.pg_catalog.tables.PgUserMappings;
import com.cf.pg_catalog.tables.PgViews;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pg_catalog
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pg_catalog.pg_aggregate</code>.
     */
    public static final PgAggregate PG_AGGREGATE = PgAggregate.PG_AGGREGATE;

    /**
     * The table <code>pg_catalog.pg_am</code>.
     */
    public static final PgAm PG_AM = PgAm.PG_AM;

    /**
     * The table <code>pg_catalog.pg_amop</code>.
     */
    public static final PgAmop PG_AMOP = PgAmop.PG_AMOP;

    /**
     * The table <code>pg_catalog.pg_amproc</code>.
     */
    public static final PgAmproc PG_AMPROC = PgAmproc.PG_AMPROC;

    /**
     * The table <code>pg_catalog.pg_attrdef</code>.
     */
    public static final PgAttrdef PG_ATTRDEF = PgAttrdef.PG_ATTRDEF;

    /**
     * The table <code>pg_catalog.pg_attribute</code>.
     */
    public static final PgAttribute PG_ATTRIBUTE = PgAttribute.PG_ATTRIBUTE;

    /**
     * The table <code>pg_catalog.pg_auth_members</code>.
     */
    public static final PgAuthMembers PG_AUTH_MEMBERS = PgAuthMembers.PG_AUTH_MEMBERS;

    /**
     * The table <code>pg_catalog.pg_available_extension_versions</code>.
     */
    public static final PgAvailableExtensionVersions PG_AVAILABLE_EXTENSION_VERSIONS = PgAvailableExtensionVersions.PG_AVAILABLE_EXTENSION_VERSIONS;

    /**
     * The table <code>pg_catalog.pg_available_extensions</code>.
     */
    public static final PgAvailableExtensions PG_AVAILABLE_EXTENSIONS = PgAvailableExtensions.PG_AVAILABLE_EXTENSIONS;

    /**
     * The table <code>pg_catalog.pg_cast</code>.
     */
    public static final PgCast PG_CAST = PgCast.PG_CAST;

    /**
     * The table <code>pg_catalog.pg_class</code>.
     */
    public static final PgClass PG_CLASS = PgClass.PG_CLASS;

    /**
     * The table <code>pg_catalog.pg_collation</code>.
     */
    public static final PgCollation PG_COLLATION = PgCollation.PG_COLLATION;

    /**
     * The table <code>pg_catalog.pg_constraint</code>.
     */
    public static final PgConstraint PG_CONSTRAINT = PgConstraint.PG_CONSTRAINT;

    /**
     * The table <code>pg_catalog.pg_conversion</code>.
     */
    public static final PgConversion PG_CONVERSION = PgConversion.PG_CONVERSION;

    /**
     * The table <code>pg_catalog.pg_cursors</code>.
     */
    public static final PgCursors PG_CURSORS = PgCursors.PG_CURSORS;

    /**
     * The table <code>pg_catalog.pg_database</code>.
     */
    public static final PgDatabase PG_DATABASE = PgDatabase.PG_DATABASE;

    /**
     * The table <code>pg_catalog.pg_db_role_setting</code>.
     */
    public static final PgDbRoleSetting PG_DB_ROLE_SETTING = PgDbRoleSetting.PG_DB_ROLE_SETTING;

    /**
     * The table <code>pg_catalog.pg_default_acl</code>.
     */
    public static final PgDefaultAcl PG_DEFAULT_ACL = PgDefaultAcl.PG_DEFAULT_ACL;

    /**
     * The table <code>pg_catalog.pg_depend</code>.
     */
    public static final PgDepend PG_DEPEND = PgDepend.PG_DEPEND;

    /**
     * The table <code>pg_catalog.pg_description</code>.
     */
    public static final PgDescription PG_DESCRIPTION = PgDescription.PG_DESCRIPTION;

    /**
     * The table <code>pg_catalog.pg_enum</code>.
     */
    public static final PgEnum PG_ENUM = PgEnum.PG_ENUM;

    /**
     * The table <code>pg_catalog.pg_event_trigger</code>.
     */
    public static final PgEventTrigger PG_EVENT_TRIGGER = PgEventTrigger.PG_EVENT_TRIGGER;

    /**
     * The table <code>pg_catalog.pg_extension</code>.
     */
    public static final PgExtension PG_EXTENSION = PgExtension.PG_EXTENSION;

    /**
     * The table <code>pg_catalog.pg_foreign_data_wrapper</code>.
     */
    public static final PgForeignDataWrapper PG_FOREIGN_DATA_WRAPPER = PgForeignDataWrapper.PG_FOREIGN_DATA_WRAPPER;

    /**
     * The table <code>pg_catalog.pg_foreign_server</code>.
     */
    public static final PgForeignServer PG_FOREIGN_SERVER = PgForeignServer.PG_FOREIGN_SERVER;

    /**
     * The table <code>pg_catalog.pg_foreign_table</code>.
     */
    public static final PgForeignTable PG_FOREIGN_TABLE = PgForeignTable.PG_FOREIGN_TABLE;

    /**
     * The table <code>pg_catalog.pg_group</code>.
     */
    public static final PgGroup PG_GROUP = PgGroup.PG_GROUP;

    /**
     * The table <code>pg_catalog.pg_index</code>.
     */
    public static final PgIndex PG_INDEX = PgIndex.PG_INDEX;

    /**
     * The table <code>pg_catalog.pg_indexes</code>.
     */
    public static final PgIndexes PG_INDEXES = PgIndexes.PG_INDEXES;

    /**
     * The table <code>pg_catalog.pg_inherits</code>.
     */
    public static final PgInherits PG_INHERITS = PgInherits.PG_INHERITS;

    /**
     * The table <code>pg_catalog.pg_language</code>.
     */
    public static final PgLanguage PG_LANGUAGE = PgLanguage.PG_LANGUAGE;

    /**
     * The table <code>pg_catalog.pg_largeobject_metadata</code>.
     */
    public static final PgLargeobjectMetadata PG_LARGEOBJECT_METADATA = PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA;

    /**
     * The table <code>pg_catalog.pg_locks</code>.
     */
    public static final PgLocks PG_LOCKS = PgLocks.PG_LOCKS;

    /**
     * The table <code>pg_catalog.pg_matviews</code>.
     */
    public static final PgMatviews PG_MATVIEWS = PgMatviews.PG_MATVIEWS;

    /**
     * The table <code>pg_catalog.pg_namespace</code>.
     */
    public static final PgNamespace PG_NAMESPACE = PgNamespace.PG_NAMESPACE;

    /**
     * The table <code>pg_catalog.pg_opclass</code>.
     */
    public static final PgOpclass PG_OPCLASS = PgOpclass.PG_OPCLASS;

    /**
     * The table <code>pg_catalog.pg_operator</code>.
     */
    public static final PgOperator PG_OPERATOR = PgOperator.PG_OPERATOR;

    /**
     * The table <code>pg_catalog.pg_opfamily</code>.
     */
    public static final PgOpfamily PG_OPFAMILY = PgOpfamily.PG_OPFAMILY;

    /**
     * The table <code>pg_catalog.pg_pltemplate</code>.
     */
    public static final PgPltemplate PG_PLTEMPLATE = PgPltemplate.PG_PLTEMPLATE;

    /**
     * The table <code>pg_catalog.pg_policies</code>.
     */
    public static final PgPolicies PG_POLICIES = PgPolicies.PG_POLICIES;

    /**
     * The table <code>pg_catalog.pg_policy</code>.
     */
    public static final PgPolicy PG_POLICY = PgPolicy.PG_POLICY;

    /**
     * The table <code>pg_catalog.pg_prepared_statements</code>.
     */
    public static final PgPreparedStatements PG_PREPARED_STATEMENTS = PgPreparedStatements.PG_PREPARED_STATEMENTS;

    /**
     * The table <code>pg_catalog.pg_prepared_xacts</code>.
     */
    public static final PgPreparedXacts PG_PREPARED_XACTS = PgPreparedXacts.PG_PREPARED_XACTS;

    /**
     * The table <code>pg_catalog.pg_proc</code>.
     */
    public static final PgProc PG_PROC = PgProc.PG_PROC;

    /**
     * The table <code>pg_catalog.pg_range</code>.
     */
    public static final PgRange PG_RANGE = PgRange.PG_RANGE;

    /**
     * The table <code>pg_catalog.pg_replication_origin</code>.
     */
    public static final PgReplicationOrigin PG_REPLICATION_ORIGIN = PgReplicationOrigin.PG_REPLICATION_ORIGIN;

    /**
     * The table <code>pg_catalog.pg_replication_slots</code>.
     */
    public static final PgReplicationSlots PG_REPLICATION_SLOTS = PgReplicationSlots.PG_REPLICATION_SLOTS;

    /**
     * The table <code>pg_catalog.pg_rewrite</code>.
     */
    public static final PgRewrite PG_REWRITE = PgRewrite.PG_REWRITE;

    /**
     * The table <code>pg_catalog.pg_roles</code>.
     */
    public static final PgRoles PG_ROLES = PgRoles.PG_ROLES;

    /**
     * The table <code>pg_catalog.pg_rules</code>.
     */
    public static final PgRules PG_RULES = PgRules.PG_RULES;

    /**
     * The table <code>pg_catalog.pg_seclabel</code>.
     */
    public static final PgSeclabel PG_SECLABEL = PgSeclabel.PG_SECLABEL;

    /**
     * The table <code>pg_catalog.pg_seclabels</code>.
     */
    public static final PgSeclabels PG_SECLABELS = PgSeclabels.PG_SECLABELS;

    /**
     * The table <code>pg_catalog.pg_settings</code>.
     */
    public static final PgSettings PG_SETTINGS = PgSettings.PG_SETTINGS;

    /**
     * The table <code>pg_catalog.pg_shdepend</code>.
     */
    public static final PgShdepend PG_SHDEPEND = PgShdepend.PG_SHDEPEND;

    /**
     * The table <code>pg_catalog.pg_shdescription</code>.
     */
    public static final PgShdescription PG_SHDESCRIPTION = PgShdescription.PG_SHDESCRIPTION;

    /**
     * The table <code>pg_catalog.pg_shseclabel</code>.
     */
    public static final PgShseclabel PG_SHSECLABEL = PgShseclabel.PG_SHSECLABEL;

    /**
     * The table <code>pg_catalog.pg_stat_activity</code>.
     */
    public static final PgStatActivity PG_STAT_ACTIVITY = PgStatActivity.PG_STAT_ACTIVITY;

    /**
     * The table <code>pg_catalog.pg_stat_all_indexes</code>.
     */
    public static final PgStatAllIndexes PG_STAT_ALL_INDEXES = PgStatAllIndexes.PG_STAT_ALL_INDEXES;

    /**
     * The table <code>pg_catalog.pg_stat_all_tables</code>.
     */
    public static final PgStatAllTables PG_STAT_ALL_TABLES = PgStatAllTables.PG_STAT_ALL_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_archiver</code>.
     */
    public static final PgStatArchiver PG_STAT_ARCHIVER = PgStatArchiver.PG_STAT_ARCHIVER;

    /**
     * The table <code>pg_catalog.pg_stat_bgwriter</code>.
     */
    public static final PgStatBgwriter PG_STAT_BGWRITER = PgStatBgwriter.PG_STAT_BGWRITER;

    /**
     * The table <code>pg_catalog.pg_stat_database</code>.
     */
    public static final PgStatDatabase PG_STAT_DATABASE = PgStatDatabase.PG_STAT_DATABASE;

    /**
     * The table <code>pg_catalog.pg_stat_database_conflicts</code>.
     */
    public static final PgStatDatabaseConflicts PG_STAT_DATABASE_CONFLICTS = PgStatDatabaseConflicts.PG_STAT_DATABASE_CONFLICTS;

    /**
     * The table <code>pg_catalog.pg_stat_replication</code>.
     */
    public static final PgStatReplication PG_STAT_REPLICATION = PgStatReplication.PG_STAT_REPLICATION;

    /**
     * The table <code>pg_catalog.pg_stat_ssl</code>.
     */
    public static final PgStatSsl PG_STAT_SSL = PgStatSsl.PG_STAT_SSL;

    /**
     * The table <code>pg_catalog.pg_stat_sys_indexes</code>.
     */
    public static final PgStatSysIndexes PG_STAT_SYS_INDEXES = PgStatSysIndexes.PG_STAT_SYS_INDEXES;

    /**
     * The table <code>pg_catalog.pg_stat_sys_tables</code>.
     */
    public static final PgStatSysTables PG_STAT_SYS_TABLES = PgStatSysTables.PG_STAT_SYS_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_user_functions</code>.
     */
    public static final PgStatUserFunctions PG_STAT_USER_FUNCTIONS = PgStatUserFunctions.PG_STAT_USER_FUNCTIONS;

    /**
     * The table <code>pg_catalog.pg_stat_user_indexes</code>.
     */
    public static final PgStatUserIndexes PG_STAT_USER_INDEXES = PgStatUserIndexes.PG_STAT_USER_INDEXES;

    /**
     * The table <code>pg_catalog.pg_stat_user_tables</code>.
     */
    public static final PgStatUserTables PG_STAT_USER_TABLES = PgStatUserTables.PG_STAT_USER_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_xact_all_tables</code>.
     */
    public static final PgStatXactAllTables PG_STAT_XACT_ALL_TABLES = PgStatXactAllTables.PG_STAT_XACT_ALL_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_xact_sys_tables</code>.
     */
    public static final PgStatXactSysTables PG_STAT_XACT_SYS_TABLES = PgStatXactSysTables.PG_STAT_XACT_SYS_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_xact_user_functions</code>.
     */
    public static final PgStatXactUserFunctions PG_STAT_XACT_USER_FUNCTIONS = PgStatXactUserFunctions.PG_STAT_XACT_USER_FUNCTIONS;

    /**
     * The table <code>pg_catalog.pg_stat_xact_user_tables</code>.
     */
    public static final PgStatXactUserTables PG_STAT_XACT_USER_TABLES = PgStatXactUserTables.PG_STAT_XACT_USER_TABLES;

    /**
     * The table <code>pg_catalog.pg_statio_all_indexes</code>.
     */
    public static final PgStatioAllIndexes PG_STATIO_ALL_INDEXES = PgStatioAllIndexes.PG_STATIO_ALL_INDEXES;

    /**
     * The table <code>pg_catalog.pg_statio_all_sequences</code>.
     */
    public static final PgStatioAllSequences PG_STATIO_ALL_SEQUENCES = PgStatioAllSequences.PG_STATIO_ALL_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_statio_all_tables</code>.
     */
    public static final PgStatioAllTables PG_STATIO_ALL_TABLES = PgStatioAllTables.PG_STATIO_ALL_TABLES;

    /**
     * The table <code>pg_catalog.pg_statio_sys_indexes</code>.
     */
    public static final PgStatioSysIndexes PG_STATIO_SYS_INDEXES = PgStatioSysIndexes.PG_STATIO_SYS_INDEXES;

    /**
     * The table <code>pg_catalog.pg_statio_sys_sequences</code>.
     */
    public static final PgStatioSysSequences PG_STATIO_SYS_SEQUENCES = PgStatioSysSequences.PG_STATIO_SYS_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_statio_sys_tables</code>.
     */
    public static final PgStatioSysTables PG_STATIO_SYS_TABLES = PgStatioSysTables.PG_STATIO_SYS_TABLES;

    /**
     * The table <code>pg_catalog.pg_statio_user_indexes</code>.
     */
    public static final PgStatioUserIndexes PG_STATIO_USER_INDEXES = PgStatioUserIndexes.PG_STATIO_USER_INDEXES;

    /**
     * The table <code>pg_catalog.pg_statio_user_sequences</code>.
     */
    public static final PgStatioUserSequences PG_STATIO_USER_SEQUENCES = PgStatioUserSequences.PG_STATIO_USER_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_statio_user_tables</code>.
     */
    public static final PgStatioUserTables PG_STATIO_USER_TABLES = PgStatioUserTables.PG_STATIO_USER_TABLES;

    /**
     * The table <code>pg_catalog.pg_stats</code>.
     */
    public static final PgStats PG_STATS = PgStats.PG_STATS;

    /**
     * The table <code>pg_catalog.pg_tables</code>.
     */
    public static final PgTables PG_TABLES = PgTables.PG_TABLES;

    /**
     * The table <code>pg_catalog.pg_tablespace</code>.
     */
    public static final PgTablespace PG_TABLESPACE = PgTablespace.PG_TABLESPACE;

    /**
     * The table <code>pg_catalog.pg_timezone_abbrevs</code>.
     */
    public static final PgTimezoneAbbrevs PG_TIMEZONE_ABBREVS = PgTimezoneAbbrevs.PG_TIMEZONE_ABBREVS;

    /**
     * The table <code>pg_catalog.pg_timezone_names</code>.
     */
    public static final PgTimezoneNames PG_TIMEZONE_NAMES = PgTimezoneNames.PG_TIMEZONE_NAMES;

    /**
     * The table <code>pg_catalog.pg_transform</code>.
     */
    public static final PgTransform PG_TRANSFORM = PgTransform.PG_TRANSFORM;

    /**
     * The table <code>pg_catalog.pg_trigger</code>.
     */
    public static final PgTrigger PG_TRIGGER = PgTrigger.PG_TRIGGER;

    /**
     * The table <code>pg_catalog.pg_ts_config</code>.
     */
    public static final PgTsConfig PG_TS_CONFIG = PgTsConfig.PG_TS_CONFIG;

    /**
     * The table <code>pg_catalog.pg_ts_config_map</code>.
     */
    public static final PgTsConfigMap PG_TS_CONFIG_MAP = PgTsConfigMap.PG_TS_CONFIG_MAP;

    /**
     * The table <code>pg_catalog.pg_ts_dict</code>.
     */
    public static final PgTsDict PG_TS_DICT = PgTsDict.PG_TS_DICT;

    /**
     * The table <code>pg_catalog.pg_ts_parser</code>.
     */
    public static final PgTsParser PG_TS_PARSER = PgTsParser.PG_TS_PARSER;

    /**
     * The table <code>pg_catalog.pg_ts_template</code>.
     */
    public static final PgTsTemplate PG_TS_TEMPLATE = PgTsTemplate.PG_TS_TEMPLATE;

    /**
     * The table <code>pg_catalog.pg_type</code>.
     */
    public static final PgType PG_TYPE = PgType.PG_TYPE;

    /**
     * The table <code>pg_catalog.pg_user</code>.
     */
    public static final PgUser PG_USER = PgUser.PG_USER;

    /**
     * The table <code>pg_catalog.pg_user_mappings</code>.
     */
    public static final PgUserMappings PG_USER_MAPPINGS = PgUserMappings.PG_USER_MAPPINGS;

    /**
     * The table <code>pg_catalog.pg_views</code>.
     */
    public static final PgViews PG_VIEWS = PgViews.PG_VIEWS;
}
