/*
 * This file is generated by jOOQ.
*/
package com.cf.testdb.tables.records;


import com.cf.testdb.tables.Laptop;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LaptopRecord extends TableRecordImpl<LaptopRecord> implements Record4<String, String, String, Integer> {

    private static final long serialVersionUID = 253837243;

    /**
     * Setter for <code>testdb.laptop.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.laptop.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>testdb.laptop.brand</code>.
     */
    public void setBrand(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.laptop.brand</code>.
     */
    public String getBrand() {
        return (String) get(1);
    }

    /**
     * Setter for <code>testdb.laptop.gpu</code>.
     */
    public void setGpu(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb.laptop.gpu</code>.
     */
    public String getGpu() {
        return (String) get(2);
    }

    /**
     * Setter for <code>testdb.laptop.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>testdb.laptop.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Laptop.LAPTOP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Laptop.LAPTOP.BRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Laptop.LAPTOP.GPU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Laptop.LAPTOP.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGpu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGpu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LaptopRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LaptopRecord value2(String value) {
        setBrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LaptopRecord value3(String value) {
        setGpu(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LaptopRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LaptopRecord values(String value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LaptopRecord
     */
    public LaptopRecord() {
        super(Laptop.LAPTOP);
    }

    /**
     * Create a detached, initialised LaptopRecord
     */
    public LaptopRecord(String name, String brand, String gpu, Integer price) {
        super(Laptop.LAPTOP);

        set(0, name);
        set(1, brand);
        set(2, gpu);
        set(3, price);
    }
}
