/*
 * This file is generated by jOOQ.
*/
package com.cf.uni.jooq.models.tables;


import com.cf.uni.jooq.models.Indexes;
import com.cf.uni.jooq.models.Keys;
import com.cf.uni.jooq.models.Public;
import com.cf.uni.jooq.models.tables.records.UniRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uni extends TableImpl<UniRecord> {

    private static final long serialVersionUID = -840073659;

    /**
     * The reference instance of <code>public.uni</code>
     */
    public static final Uni UNI = new Uni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UniRecord> getRecordType() {
        return UniRecord.class;
    }

    /**
     * The column <code>public.uni.id</code>.
     */
    public final TableField<UniRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.uni.name</code>.
     */
    public final TableField<UniRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.uni.city</code>.
     */
    public final TableField<UniRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.uni.country</code>.
     */
    public final TableField<UniRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.uni</code> table reference
     */
    public Uni() {
        this(DSL.name("uni"), null);
    }

    /**
     * Create an aliased <code>public.uni</code> table reference
     */
    public Uni(String alias) {
        this(DSL.name(alias), UNI);
    }

    /**
     * Create an aliased <code>public.uni</code> table reference
     */
    public Uni(Name alias) {
        this(alias, UNI);
    }

    private Uni(Name alias, Table<UniRecord> aliased) {
        this(alias, aliased, null);
    }

    private Uni(Name alias, Table<UniRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UNI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UniRecord> getPrimaryKey() {
        return Keys.UNI_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UniRecord>> getKeys() {
        return Arrays.<UniqueKey<UniRecord>>asList(Keys.UNI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uni as(String alias) {
        return new Uni(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uni as(Name alias) {
        return new Uni(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Uni rename(String name) {
        return new Uni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Uni rename(Name name) {
        return new Uni(name, null);
    }
}
