/*
 * This file is generated by jOOQ.
*/
package com.cf.uni.jooq.models;


import com.cf.uni.jooq.models.tables.Uni;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UNI_PKEY = Indexes0.UNI_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index UNI_PKEY = Internal.createIndex("uni_pkey", Uni.UNI, new OrderField[] { Uni.UNI.ID }, true);
    }
}
