/*
 * This file is generated by jOOQ.
*/
package com.cf.uni.jooq.models;


import com.cf.uni.jooq.models.tables.Uni;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.uni</code>.
     */
    public static final Uni UNI = com.cf.uni.jooq.models.tables.Uni.UNI;
}
