/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgAvailableExtensionVersions extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 179258378;

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.name</code>.
     */
    public static final Parameter<String> NAME = createParameter("name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.version</code>.
     */
    public static final Parameter<String> VERSION = createParameter("version", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.superuser</code>.
     */
    public static final Parameter<Boolean> SUPERUSER = createParameter("superuser", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.relocatable</code>.
     */
    public static final Parameter<Boolean> RELOCATABLE = createParameter("relocatable", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.schema</code>.
     */
    public static final Parameter<String> SCHEMA = createParameter("schema", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.requires</code>.
     */
    public static final Parameter<String[]> REQUIRES = createParameter("requires", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), false, false);

    /**
     * The parameter <code>pg_catalog.pg_available_extension_versions.comment</code>.
     */
    public static final Parameter<String> COMMENT = createParameter("comment", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public PgAvailableExtensionVersions() {
        super("pg_available_extension_versions", PgCatalog.PG_CATALOG);

        addOutParameter(NAME);
        addOutParameter(VERSION);
        addOutParameter(SUPERUSER);
        addOutParameter(RELOCATABLE);
        addOutParameter(SCHEMA);
        addOutParameter(REQUIRES);
        addOutParameter(COMMENT);
    }

    /**
     * Get the <code>name</code> parameter OUT value from the routine
     */
    public String getName_() {
        return get(NAME);
    }

    /**
     * Get the <code>version</code> parameter OUT value from the routine
     */
    public String getVersion() {
        return get(VERSION);
    }

    /**
     * Get the <code>superuser</code> parameter OUT value from the routine
     */
    public Boolean getSuperuser() {
        return get(SUPERUSER);
    }

    /**
     * Get the <code>relocatable</code> parameter OUT value from the routine
     */
    public Boolean getRelocatable() {
        return get(RELOCATABLE);
    }

    /**
     * Get the <code>schema</code> parameter OUT value from the routine
     */
    public String getSchema_() {
        return get(SCHEMA);
    }

    /**
     * Get the <code>requires</code> parameter OUT value from the routine
     */
    public String[] getRequires() {
        return get(REQUIRES);
    }

    /**
     * Get the <code>comment</code> parameter OUT value from the routine
     */
    public String getComment() {
        return get(COMMENT);
    }
}
