/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgCreateLogicalReplicationSlot extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 925907736;

    /**
     * The parameter <code>pg_catalog.pg_create_logical_replication_slot.slot_name</code>.
     */
    public static final Parameter<String> SLOT_NAME = createParameter("slot_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_create_logical_replication_slot.plugin</code>.
     */
    public static final Parameter<String> PLUGIN = createParameter("plugin", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_create_logical_replication_slot.slot_name</code>.
     */
    public static final Parameter<String> SLOT_NAME = createParameter("slot_name", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_create_logical_replication_slot.xlog_position</code>.
     */
    public static final Parameter<Object> XLOG_POSITION = createParameter("xlog_position", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_lsn"), false, false);

    /**
     * Create a new routine call instance
     */
    public PgCreateLogicalReplicationSlot() {
        super("pg_create_logical_replication_slot", PgCatalog.PG_CATALOG);

        addInOutParameter(SLOT_NAME);
        addInParameter(PLUGIN);
        addInOutParameter(SLOT_NAME);
        addOutParameter(XLOG_POSITION);
    }

    /**
     * Set the <code>slot_name</code> parameter IN value to the routine
     */
    public void setSlotName(String value) {
        setValue(SLOT_NAME, value);
    }

    /**
     * Set the <code>plugin</code> parameter IN value to the routine
     */
    public void setPlugin(String value) {
        setValue(PLUGIN, value);
    }

    /**
     * Get the <code>slot_name</code> parameter OUT value from the routine
     */
    public String getSlotName() {
        return get(SLOT_NAME);
    }

    /**
     * Get the <code>slot_name</code> parameter OUT value from the routine
     */
    public String getSlotName() {
        return get(SLOT_NAME);
    }

    /**
     * Get the <code>xlog_position</code> parameter OUT value from the routine
     */
    public Object getXlogPosition() {
        return get(XLOG_POSITION);
    }
}
