/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgCurrentXlogLocation extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 841683335;

    /**
     * The parameter <code>pg_catalog.pg_current_xlog_location.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_lsn"), false, false);

    /**
     * Create a new routine call instance
     */
    public PgCurrentXlogLocation() {
        super("pg_current_xlog_location", PgCatalog.PG_CATALOG, org.jooq.impl.DefaultDataType.getDefaultDataType("pg_lsn"));

        setReturnParameter(RETURN_VALUE);
    }
}
