/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgEventTriggerDroppedObjects extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -2036448028;

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.classid</code>.
     */
    public static final Parameter<Long> CLASSID = createParameter("classid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.objid</code>.
     */
    public static final Parameter<Long> OBJID = createParameter("objid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.objsubid</code>.
     */
    public static final Parameter<Integer> OBJSUBID = createParameter("objsubid", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.original</code>.
     */
    public static final Parameter<Boolean> ORIGINAL = createParameter("original", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.normal</code>.
     */
    public static final Parameter<Boolean> NORMAL = createParameter("normal", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.is_temporary</code>.
     */
    public static final Parameter<Boolean> IS_TEMPORARY = createParameter("is_temporary", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.object_type</code>.
     */
    public static final Parameter<String> OBJECT_TYPE = createParameter("object_type", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.schema_name</code>.
     */
    public static final Parameter<String> SCHEMA_NAME = createParameter("schema_name", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.object_name</code>.
     */
    public static final Parameter<String> OBJECT_NAME = createParameter("object_name", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.object_identity</code>.
     */
    public static final Parameter<String> OBJECT_IDENTITY = createParameter("object_identity", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.address_names</code>.
     */
    public static final Parameter<String[]> ADDRESS_NAMES = createParameter("address_names", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), false, false);

    /**
     * The parameter <code>pg_catalog.pg_event_trigger_dropped_objects.address_args</code>.
     */
    public static final Parameter<String[]> ADDRESS_ARGS = createParameter("address_args", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), false, false);

    /**
     * Create a new routine call instance
     */
    public PgEventTriggerDroppedObjects() {
        super("pg_event_trigger_dropped_objects", PgCatalog.PG_CATALOG);

        addOutParameter(CLASSID);
        addOutParameter(OBJID);
        addOutParameter(OBJSUBID);
        addOutParameter(ORIGINAL);
        addOutParameter(NORMAL);
        addOutParameter(IS_TEMPORARY);
        addOutParameter(OBJECT_TYPE);
        addOutParameter(SCHEMA_NAME);
        addOutParameter(OBJECT_NAME);
        addOutParameter(OBJECT_IDENTITY);
        addOutParameter(ADDRESS_NAMES);
        addOutParameter(ADDRESS_ARGS);
    }

    /**
     * Get the <code>classid</code> parameter OUT value from the routine
     */
    public Long getClassid() {
        return get(CLASSID);
    }

    /**
     * Get the <code>objid</code> parameter OUT value from the routine
     */
    public Long getObjid() {
        return get(OBJID);
    }

    /**
     * Get the <code>objsubid</code> parameter OUT value from the routine
     */
    public Integer getObjsubid() {
        return get(OBJSUBID);
    }

    /**
     * Get the <code>original</code> parameter OUT value from the routine
     */
    public Boolean getOriginal() {
        return get(ORIGINAL);
    }

    /**
     * Get the <code>normal</code> parameter OUT value from the routine
     */
    public Boolean getNormal() {
        return get(NORMAL);
    }

    /**
     * Get the <code>is_temporary</code> parameter OUT value from the routine
     */
    public Boolean getIsTemporary() {
        return get(IS_TEMPORARY);
    }

    /**
     * Get the <code>object_type</code> parameter OUT value from the routine
     */
    public String getObjectType() {
        return get(OBJECT_TYPE);
    }

    /**
     * Get the <code>schema_name</code> parameter OUT value from the routine
     */
    public String getSchemaName() {
        return get(SCHEMA_NAME);
    }

    /**
     * Get the <code>object_name</code> parameter OUT value from the routine
     */
    public String getObjectName() {
        return get(OBJECT_NAME);
    }

    /**
     * Get the <code>object_identity</code> parameter OUT value from the routine
     */
    public String getObjectIdentity() {
        return get(OBJECT_IDENTITY);
    }

    /**
     * Get the <code>address_names</code> parameter OUT value from the routine
     */
    public String[] getAddressNames() {
        return get(ADDRESS_NAMES);
    }

    /**
     * Get the <code>address_args</code> parameter OUT value from the routine
     */
    public String[] getAddressArgs() {
        return get(ADDRESS_ARGS);
    }
}
