/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGetKeywords extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -2045469174;

    /**
     * The parameter <code>pg_catalog.pg_get_keywords.word</code>.
     */
    public static final Parameter<String> WORD = createParameter("word", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_keywords.catcode</code>.
     */
    public static final Parameter<String> CATCODE = createParameter("catcode", org.jooq.impl.SQLDataType.CHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_keywords.catdesc</code>.
     */
    public static final Parameter<String> CATDESC = createParameter("catdesc", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public PgGetKeywords() {
        super("pg_get_keywords", PgCatalog.PG_CATALOG);

        addOutParameter(WORD);
        addOutParameter(CATCODE);
        addOutParameter(CATDESC);
    }

    /**
     * Get the <code>word</code> parameter OUT value from the routine
     */
    public String getWord() {
        return get(WORD);
    }

    /**
     * Get the <code>catcode</code> parameter OUT value from the routine
     */
    public String getCatcode() {
        return get(CATCODE);
    }

    /**
     * Get the <code>catdesc</code> parameter OUT value from the routine
     */
    public String getCatdesc() {
        return get(CATDESC);
    }
}
