/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGetReplicationSlots extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -1595829352;

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.slot_name</code>.
     */
    public static final Parameter<String> SLOT_NAME = createParameter("slot_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.plugin</code>.
     */
    public static final Parameter<String> PLUGIN = createParameter("plugin", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.slot_type</code>.
     */
    public static final Parameter<String> SLOT_TYPE = createParameter("slot_type", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.datoid</code>.
     */
    public static final Parameter<Long> DATOID = createParameter("datoid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.active</code>.
     */
    public static final Parameter<Boolean> ACTIVE = createParameter("active", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.active_pid</code>.
     */
    public static final Parameter<Integer> ACTIVE_PID = createParameter("active_pid", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.xmin</code>.
     */
    public static final Parameter<Long> XMIN = createParameter("xmin", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.catalog_xmin</code>.
     */
    public static final Parameter<Long> CATALOG_XMIN = createParameter("catalog_xmin", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_replication_slots.restart_lsn</code>.
     */
    public static final Parameter<Object> RESTART_LSN = createParameter("restart_lsn", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_lsn"), false, false);

    /**
     * Create a new routine call instance
     */
    public PgGetReplicationSlots() {
        super("pg_get_replication_slots", PgCatalog.PG_CATALOG);

        addOutParameter(SLOT_NAME);
        addOutParameter(PLUGIN);
        addOutParameter(SLOT_TYPE);
        addOutParameter(DATOID);
        addOutParameter(ACTIVE);
        addOutParameter(ACTIVE_PID);
        addOutParameter(XMIN);
        addOutParameter(CATALOG_XMIN);
        addOutParameter(RESTART_LSN);
    }

    /**
     * Get the <code>slot_name</code> parameter OUT value from the routine
     */
    public String getSlotName() {
        return get(SLOT_NAME);
    }

    /**
     * Get the <code>plugin</code> parameter OUT value from the routine
     */
    public String getPlugin() {
        return get(PLUGIN);
    }

    /**
     * Get the <code>slot_type</code> parameter OUT value from the routine
     */
    public String getSlotType() {
        return get(SLOT_TYPE);
    }

    /**
     * Get the <code>datoid</code> parameter OUT value from the routine
     */
    public Long getDatoid() {
        return get(DATOID);
    }

    /**
     * Get the <code>active</code> parameter OUT value from the routine
     */
    public Boolean getActive() {
        return get(ACTIVE);
    }

    /**
     * Get the <code>active_pid</code> parameter OUT value from the routine
     */
    public Integer getActivePid() {
        return get(ACTIVE_PID);
    }

    /**
     * Get the <code>xmin</code> parameter OUT value from the routine
     */
    public Long getXmin() {
        return get(XMIN);
    }

    /**
     * Get the <code>catalog_xmin</code> parameter OUT value from the routine
     */
    public Long getCatalogXmin() {
        return get(CATALOG_XMIN);
    }

    /**
     * Get the <code>restart_lsn</code> parameter OUT value from the routine
     */
    public Object getRestartLsn() {
        return get(RESTART_LSN);
    }
}
