/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGetMultixactMembers extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 1532945696;

    /**
     * The parameter <code>pg_catalog.pg_get_multixact_members.multixid</code>.
     */
    public static final Parameter<Long> MULTIXID = createParameter("multixid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_multixact_members.xid</code>.
     */
    public static final Parameter<Long> XID = createParameter("xid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_get_multixact_members.mode</code>.
     */
    public static final Parameter<String> MODE = createParameter("mode", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public PgGetMultixactMembers() {
        super("pg_get_multixact_members", PgCatalog.PG_CATALOG);

        addInParameter(MULTIXID);
        addOutParameter(XID);
        addOutParameter(MODE);
    }

    /**
     * Set the <code>multixid</code> parameter IN value to the routine
     */
    public void setMultixid(Long value) {
        setValue(MULTIXID, value);
    }

    /**
     * Get the <code>xid</code> parameter OUT value from the routine
     */
    public Long getXid() {
        return get(XID);
    }

    /**
     * Get the <code>mode</code> parameter OUT value from the routine
     */
    public String getMode() {
        return get(MODE);
    }
}
