/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgLogicalSlotPeekBinaryChanges extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 259782588;

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.slot_name</code>.
     */
    public static final Parameter<String> SLOT_NAME = createParameter("slot_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.upto_lsn</code>.
     */
    public static final Parameter<Object> UPTO_LSN = createParameter("upto_lsn", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_lsn"), false, false);

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.upto_nchanges</code>.
     */
    public static final Parameter<Integer> UPTO_NCHANGES = createParameter("upto_nchanges", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.options</code>.
     */
    public static final Parameter<String[]> OPTIONS = createParameter("options", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), false, false);

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.location</code>.
     */
    public static final Parameter<Object> LOCATION = createParameter("location", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_lsn"), false, false);

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.xid</code>.
     */
    public static final Parameter<Long> XID = createParameter("xid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_logical_slot_peek_binary_changes.data</code>.
     */
    public static final Parameter<byte[]> DATA = createParameter("data", org.jooq.impl.SQLDataType.BLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public PgLogicalSlotPeekBinaryChanges() {
        super("pg_logical_slot_peek_binary_changes", PgCatalog.PG_CATALOG);

        addInParameter(SLOT_NAME);
        addInParameter(UPTO_LSN);
        addInParameter(UPTO_NCHANGES);
        addInParameter(OPTIONS);
        addOutParameter(LOCATION);
        addOutParameter(XID);
        addOutParameter(DATA);
    }

    /**
     * Set the <code>slot_name</code> parameter IN value to the routine
     */
    public void setSlotName(String value) {
        setValue(SLOT_NAME, value);
    }

    /**
     * Set the <code>upto_lsn</code> parameter IN value to the routine
     */
    public void setUptoLsn(Object value) {
        setValue(UPTO_LSN, value);
    }

    /**
     * Set the <code>upto_nchanges</code> parameter IN value to the routine
     */
    public void setUptoNchanges(Integer value) {
        setValue(UPTO_NCHANGES, value);
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    public void setOptions(String[] value) {
        setValue(OPTIONS, value);
    }

    /**
     * Get the <code>location</code> parameter OUT value from the routine
     */
    public Object getLocation() {
        return get(LOCATION);
    }

    /**
     * Get the <code>xid</code> parameter OUT value from the routine
     */
    public Long getXid() {
        return get(XID);
    }

    /**
     * Get the <code>data</code> parameter OUT value from the routine
     */
    public byte[] getData() {
        return get(DATA);
    }
}
