/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatFile1 extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -1770827638;

    /**
     * The parameter <code>pg_catalog.pg_stat_file.filename</code>.
     */
    public static final Parameter<String> FILENAME = createParameter("filename", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.size</code>.
     */
    public static final Parameter<Long> SIZE = createParameter("size", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.access</code>.
     */
    public static final Parameter<Timestamp> ACCESS = createParameter("access", org.jooq.impl.SQLDataType.TIMESTAMP, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.modification</code>.
     */
    public static final Parameter<Timestamp> MODIFICATION = createParameter("modification", org.jooq.impl.SQLDataType.TIMESTAMP, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.change</code>.
     */
    public static final Parameter<Timestamp> CHANGE = createParameter("change", org.jooq.impl.SQLDataType.TIMESTAMP, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.creation</code>.
     */
    public static final Parameter<Timestamp> CREATION = createParameter("creation", org.jooq.impl.SQLDataType.TIMESTAMP, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.isdir</code>.
     */
    public static final Parameter<Boolean> ISDIR = createParameter("isdir", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public PgStatFile1() {
        super("pg_stat_file", PgCatalog.PG_CATALOG);

        addInParameter(FILENAME);
        addOutParameter(SIZE);
        addOutParameter(ACCESS);
        addOutParameter(MODIFICATION);
        addOutParameter(CHANGE);
        addOutParameter(CREATION);
        addOutParameter(ISDIR);
        setOverloaded(true);
    }

    /**
     * Set the <code>filename</code> parameter IN value to the routine
     */
    public void setFilename(String value) {
        setValue(FILENAME, value);
    }

    /**
     * Get the <code>size</code> parameter OUT value from the routine
     */
    public Long getSize() {
        return get(SIZE);
    }

    /**
     * Get the <code>access</code> parameter OUT value from the routine
     */
    public Timestamp getAccess() {
        return get(ACCESS);
    }

    /**
     * Get the <code>modification</code> parameter OUT value from the routine
     */
    public Timestamp getModification() {
        return get(MODIFICATION);
    }

    /**
     * Get the <code>change</code> parameter OUT value from the routine
     */
    public Timestamp getChange() {
        return get(CHANGE);
    }

    /**
     * Get the <code>creation</code> parameter OUT value from the routine
     */
    public Timestamp getCreation() {
        return get(CREATION);
    }

    /**
     * Get the <code>isdir</code> parameter OUT value from the routine
     */
    public Boolean getIsdir() {
        return get(ISDIR);
    }
}
