/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTimezoneAbbrevs extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 1102416910;

    /**
     * The parameter <code>pg_catalog.pg_timezone_abbrevs.abbrev</code>.
     */
    public static final Parameter<String> ABBREV = createParameter("abbrev", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_timezone_abbrevs.utc_offset</code>.
     */
    public static final Parameter<Object> UTC_OFFSET = createParameter("utc_offset", org.jooq.impl.DefaultDataType.getDefaultDataType("interval"), false, false);

    /**
     * The parameter <code>pg_catalog.pg_timezone_abbrevs.is_dst</code>.
     */
    public static final Parameter<Boolean> IS_DST = createParameter("is_dst", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public PgTimezoneAbbrevs() {
        super("pg_timezone_abbrevs", PgCatalog.PG_CATALOG);

        addOutParameter(ABBREV);
        addOutParameter(UTC_OFFSET);
        addOutParameter(IS_DST);
    }

    /**
     * Get the <code>abbrev</code> parameter OUT value from the routine
     */
    public String getAbbrev() {
        return get(ABBREV);
    }

    /**
     * Get the <code>utc_offset</code> parameter OUT value from the routine
     */
    public Object getUtcOffset() {
        return get(UTC_OFFSET);
    }

    /**
     * Get the <code>is_dst</code> parameter OUT value from the routine
     */
    public Boolean getIsDst() {
        return get(IS_DST);
    }
}
