/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTimezoneNames extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -1622527408;

    /**
     * The parameter <code>pg_catalog.pg_timezone_names.name</code>.
     */
    public static final Parameter<String> NAME = createParameter("name", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_timezone_names.abbrev</code>.
     */
    public static final Parameter<String> ABBREV = createParameter("abbrev", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_timezone_names.utc_offset</code>.
     */
    public static final Parameter<Object> UTC_OFFSET = createParameter("utc_offset", org.jooq.impl.DefaultDataType.getDefaultDataType("interval"), false, false);

    /**
     * The parameter <code>pg_catalog.pg_timezone_names.is_dst</code>.
     */
    public static final Parameter<Boolean> IS_DST = createParameter("is_dst", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public PgTimezoneNames() {
        super("pg_timezone_names", PgCatalog.PG_CATALOG);

        addOutParameter(NAME);
        addOutParameter(ABBREV);
        addOutParameter(UTC_OFFSET);
        addOutParameter(IS_DST);
    }

    /**
     * Get the <code>name</code> parameter OUT value from the routine
     */
    public String getName_() {
        return get(NAME);
    }

    /**
     * Get the <code>abbrev</code> parameter OUT value from the routine
     */
    public String getAbbrev() {
        return get(ABBREV);
    }

    /**
     * Get the <code>utc_offset</code> parameter OUT value from the routine
     */
    public Object getUtcOffset() {
        return get(UTC_OFFSET);
    }

    /**
     * Get the <code>is_dst</code> parameter OUT value from the routine
     */
    public Boolean getIsDst() {
        return get(IS_DST);
    }
}
