/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Timenow extends AbstractRoutine<Object> {

    private static final long serialVersionUID = -1424449787;

    /**
     * The parameter <code>pg_catalog.timenow.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("abstime"), false, false);

    /**
     * Create a new routine call instance
     */
    public Timenow() {
        super("timenow", PgCatalog.PG_CATALOG, org.jooq.impl.DefaultDataType.getDefaultDataType("abstime"));

        setReturnParameter(RETURN_VALUE);
    }
}
