/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TsStat2 extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -995160884;

    /**
     * The parameter <code>pg_catalog.ts_stat.query</code>.
     */
    public static final Parameter<String> QUERY = createParameter("query", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.ts_stat.weights</code>.
     */
    public static final Parameter<String> WEIGHTS = createParameter("weights", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.ts_stat.word</code>.
     */
    public static final Parameter<String> WORD = createParameter("word", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.ts_stat.ndoc</code>.
     */
    public static final Parameter<Integer> NDOC = createParameter("ndoc", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>pg_catalog.ts_stat.nentry</code>.
     */
    public static final Parameter<Integer> NENTRY = createParameter("nentry", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public TsStat2() {
        super("ts_stat", PgCatalog.PG_CATALOG);

        addInParameter(QUERY);
        addInParameter(WEIGHTS);
        addOutParameter(WORD);
        addOutParameter(NDOC);
        addOutParameter(NENTRY);
        setOverloaded(true);
    }

    /**
     * Set the <code>query</code> parameter IN value to the routine
     */
    public void setQuery(String value) {
        setValue(QUERY, value);
    }

    /**
     * Set the <code>weights</code> parameter IN value to the routine
     */
    public void setWeights(String value) {
        setValue(WEIGHTS, value);
    }

    /**
     * Get the <code>word</code> parameter OUT value from the routine
     */
    public String getWord() {
        return get(WORD);
    }

    /**
     * Get the <code>ndoc</code> parameter OUT value from the routine
     */
    public Integer getNdoc() {
        return get(NDOC);
    }

    /**
     * Get the <code>nentry</code> parameter OUT value from the routine
     */
    public Integer getNentry() {
        return get(NENTRY);
    }
}
