/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TsTokenType2 extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 319409866;

    /**
     * The parameter <code>pg_catalog.ts_token_type.parser_name</code>.
     */
    public static final Parameter<String> PARSER_NAME = createParameter("parser_name", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.ts_token_type.tokid</code>.
     */
    public static final Parameter<Integer> TOKID = createParameter("tokid", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>pg_catalog.ts_token_type.alias</code>.
     */
    public static final Parameter<String> ALIAS = createParameter("alias", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.ts_token_type.description</code>.
     */
    public static final Parameter<String> DESCRIPTION = createParameter("description", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public TsTokenType2() {
        super("ts_token_type", PgCatalog.PG_CATALOG);

        addInParameter(PARSER_NAME);
        addOutParameter(TOKID);
        addOutParameter(ALIAS);
        addOutParameter(DESCRIPTION);
        setOverloaded(true);
    }

    /**
     * Set the <code>parser_name</code> parameter IN value to the routine
     */
    public void setParserName(String value) {
        setValue(PARSER_NAME, value);
    }

    /**
     * Get the <code>tokid</code> parameter OUT value from the routine
     */
    public Integer getTokid() {
        return get(TOKID);
    }

    /**
     * Get the <code>alias</code> parameter OUT value from the routine
     */
    public String getAlias() {
        return get(ALIAS);
    }

    /**
     * Get the <code>description</code> parameter OUT value from the routine
     */
    public String getDescription() {
        return get(DESCRIPTION);
    }
}
