/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.routines;


import com.cf.pg_catalog.PgCatalog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tstzrange1 extends AbstractRoutine<Object> {

    private static final long serialVersionUID = -111284455;

    /**
     * The parameter <code>pg_catalog.tstzrange.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), false, false);

    /**
     * The parameter <code>pg_catalog.tstzrange._1</code>.
     */
    public static final Parameter<Timestamp> _1 = createParameter("_1", org.jooq.impl.SQLDataType.TIMESTAMP, false, true);

    /**
     * The parameter <code>pg_catalog.tstzrange._2</code>.
     */
    public static final Parameter<Timestamp> _2 = createParameter("_2", org.jooq.impl.SQLDataType.TIMESTAMP, false, true);

    /**
     * Create a new routine call instance
     */
    public Tstzrange1() {
        super("tstzrange", PgCatalog.PG_CATALOG, org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"));

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
        addInParameter(_2);
        setOverloaded(true);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(Timestamp value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__1(Field<Timestamp> field) {
        setField(_1, field);
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    public void set__2(Timestamp value) {
        setValue(_2, value);
    }

    /**
     * Set the <code>_2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__2(Field<Timestamp> field) {
        setField(_2, field);
    }
}
