/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgAm;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgAmRecord extends TableRecordImpl<PgAmRecord> {

    private static final long serialVersionUID = 1025748033;

    /**
     * Setter for <code>pg_catalog.pg_am.amname</code>.
     */
    public void setAmname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amname</code>.
     */
    public String getAmname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amstrategies</code>.
     */
    public void setAmstrategies(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amstrategies</code>.
     */
    public Short getAmstrategies() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amsupport</code>.
     */
    public void setAmsupport(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amsupport</code>.
     */
    public Short getAmsupport() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcanorder</code>.
     */
    public void setAmcanorder(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcanorder</code>.
     */
    public Boolean getAmcanorder() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcanorderbyop</code>.
     */
    public void setAmcanorderbyop(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcanorderbyop</code>.
     */
    public Boolean getAmcanorderbyop() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcanbackward</code>.
     */
    public void setAmcanbackward(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcanbackward</code>.
     */
    public Boolean getAmcanbackward() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcanunique</code>.
     */
    public void setAmcanunique(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcanunique</code>.
     */
    public Boolean getAmcanunique() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcanmulticol</code>.
     */
    public void setAmcanmulticol(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcanmulticol</code>.
     */
    public Boolean getAmcanmulticol() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amoptionalkey</code>.
     */
    public void setAmoptionalkey(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amoptionalkey</code>.
     */
    public Boolean getAmoptionalkey() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amsearcharray</code>.
     */
    public void setAmsearcharray(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amsearcharray</code>.
     */
    public Boolean getAmsearcharray() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amsearchnulls</code>.
     */
    public void setAmsearchnulls(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amsearchnulls</code>.
     */
    public Boolean getAmsearchnulls() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amstorage</code>.
     */
    public void setAmstorage(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amstorage</code>.
     */
    public Boolean getAmstorage() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amclusterable</code>.
     */
    public void setAmclusterable(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amclusterable</code>.
     */
    public Boolean getAmclusterable() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.ampredlocks</code>.
     */
    public void setAmpredlocks(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.ampredlocks</code>.
     */
    public Boolean getAmpredlocks() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amkeytype</code>.
     */
    public void setAmkeytype(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amkeytype</code>.
     */
    public Long getAmkeytype() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.aminsert</code>.
     */
    public void setAminsert(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.aminsert</code>.
     */
    public String getAminsert() {
        return (String) get(15);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.ambeginscan</code>.
     */
    public void setAmbeginscan(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.ambeginscan</code>.
     */
    public String getAmbeginscan() {
        return (String) get(16);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amgettuple</code>.
     */
    public void setAmgettuple(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amgettuple</code>.
     */
    public String getAmgettuple() {
        return (String) get(17);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amgetbitmap</code>.
     */
    public void setAmgetbitmap(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amgetbitmap</code>.
     */
    public String getAmgetbitmap() {
        return (String) get(18);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amrescan</code>.
     */
    public void setAmrescan(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amrescan</code>.
     */
    public String getAmrescan() {
        return (String) get(19);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amendscan</code>.
     */
    public void setAmendscan(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amendscan</code>.
     */
    public String getAmendscan() {
        return (String) get(20);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.ammarkpos</code>.
     */
    public void setAmmarkpos(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.ammarkpos</code>.
     */
    public String getAmmarkpos() {
        return (String) get(21);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amrestrpos</code>.
     */
    public void setAmrestrpos(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amrestrpos</code>.
     */
    public String getAmrestrpos() {
        return (String) get(22);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.ambuild</code>.
     */
    public void setAmbuild(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.ambuild</code>.
     */
    public String getAmbuild() {
        return (String) get(23);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.ambuildempty</code>.
     */
    public void setAmbuildempty(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.ambuildempty</code>.
     */
    public String getAmbuildempty() {
        return (String) get(24);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.ambulkdelete</code>.
     */
    public void setAmbulkdelete(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.ambulkdelete</code>.
     */
    public String getAmbulkdelete() {
        return (String) get(25);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amvacuumcleanup</code>.
     */
    public void setAmvacuumcleanup(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amvacuumcleanup</code>.
     */
    public String getAmvacuumcleanup() {
        return (String) get(26);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcanreturn</code>.
     */
    public void setAmcanreturn(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcanreturn</code>.
     */
    public String getAmcanreturn() {
        return (String) get(27);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amcostestimate</code>.
     */
    public void setAmcostestimate(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amcostestimate</code>.
     */
    public String getAmcostestimate() {
        return (String) get(28);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amoptions</code>.
     */
    public void setAmoptions(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amoptions</code>.
     */
    public String getAmoptions() {
        return (String) get(29);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgAmRecord
     */
    public PgAmRecord() {
        super(PgAm.PG_AM);
    }

    /**
     * Create a detached, initialised PgAmRecord
     */
    public PgAmRecord(String amname, Short amstrategies, Short amsupport, Boolean amcanorder, Boolean amcanorderbyop, Boolean amcanbackward, Boolean amcanunique, Boolean amcanmulticol, Boolean amoptionalkey, Boolean amsearcharray, Boolean amsearchnulls, Boolean amstorage, Boolean amclusterable, Boolean ampredlocks, Long amkeytype, String aminsert, String ambeginscan, String amgettuple, String amgetbitmap, String amrescan, String amendscan, String ammarkpos, String amrestrpos, String ambuild, String ambuildempty, String ambulkdelete, String amvacuumcleanup, String amcanreturn, String amcostestimate, String amoptions) {
        super(PgAm.PG_AM);

        set(0, amname);
        set(1, amstrategies);
        set(2, amsupport);
        set(3, amcanorder);
        set(4, amcanorderbyop);
        set(5, amcanbackward);
        set(6, amcanunique);
        set(7, amcanmulticol);
        set(8, amoptionalkey);
        set(9, amsearcharray);
        set(10, amsearchnulls);
        set(11, amstorage);
        set(12, amclusterable);
        set(13, ampredlocks);
        set(14, amkeytype);
        set(15, aminsert);
        set(16, ambeginscan);
        set(17, amgettuple);
        set(18, amgetbitmap);
        set(19, amrescan);
        set(20, amendscan);
        set(21, ammarkpos);
        set(22, amrestrpos);
        set(23, ambuild);
        set(24, ambuildempty);
        set(25, ambulkdelete);
        set(26, amvacuumcleanup);
        set(27, amcanreturn);
        set(28, amcostestimate);
        set(29, amoptions);
    }
}
