/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgCollation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgCollationRecord extends TableRecordImpl<PgCollationRecord> implements Record6<String, Long, Long, Integer, String, String> {

    private static final long serialVersionUID = 862561147;

    /**
     * Setter for <code>pg_catalog.pg_collation.collname</code>.
     */
    public void setCollname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_collation.collname</code>.
     */
    public String getCollname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_collation.collnamespace</code>.
     */
    public void setCollnamespace(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_collation.collnamespace</code>.
     */
    public Long getCollnamespace() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_collation.collowner</code>.
     */
    public void setCollowner(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_collation.collowner</code>.
     */
    public Long getCollowner() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_collation.collencoding</code>.
     */
    public void setCollencoding(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_collation.collencoding</code>.
     */
    public Integer getCollencoding() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_collation.collcollate</code>.
     */
    public void setCollcollate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_collation.collcollate</code>.
     */
    public String getCollcollate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_collation.collctype</code>.
     */
    public void setCollctype(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_collation.collctype</code>.
     */
    public String getCollctype() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Long, Long, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Long, Long, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PgCollation.PG_COLLATION.COLLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgCollation.PG_COLLATION.COLLNAMESPACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgCollation.PG_COLLATION.COLLOWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PgCollation.PG_COLLATION.COLLENCODING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgCollation.PG_COLLATION.COLLCOLLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgCollation.PG_COLLATION.COLLCTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCollname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCollnamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCollowner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCollencoding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCollcollate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCollctype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord value1(String value) {
        setCollname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord value2(Long value) {
        setCollnamespace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord value3(Long value) {
        setCollowner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord value4(Integer value) {
        setCollencoding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord value5(String value) {
        setCollcollate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord value6(String value) {
        setCollctype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgCollationRecord values(String value1, Long value2, Long value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgCollationRecord
     */
    public PgCollationRecord() {
        super(PgCollation.PG_COLLATION);
    }

    /**
     * Create a detached, initialised PgCollationRecord
     */
    public PgCollationRecord(String collname, Long collnamespace, Long collowner, Integer collencoding, String collcollate, String collctype) {
        super(PgCollation.PG_COLLATION);

        set(0, collname);
        set(1, collnamespace);
        set(2, collowner);
        set(3, collencoding);
        set(4, collcollate);
        set(5, collctype);
    }
}
