/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgPolicy;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPolicyRecord extends TableRecordImpl<PgPolicyRecord> implements Record6<String, Long, String, Long[], Object, Object> {

    private static final long serialVersionUID = -1516056354;

    /**
     * Setter for <code>pg_catalog.pg_policy.polname</code>.
     */
    public void setPolname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polname</code>.
     */
    public String getPolname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polrelid</code>.
     */
    public void setPolrelid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polrelid</code>.
     */
    public Long getPolrelid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polcmd</code>.
     */
    public void setPolcmd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polcmd</code>.
     */
    public String getPolcmd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polroles</code>.
     */
    public void setPolroles(Long[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polroles</code>.
     */
    public Long[] getPolroles() {
        return (Long[]) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polqual</code>.
     */
    public void setPolqual(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polqual</code>.
     */
    public Object getPolqual() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polwithcheck</code>.
     */
    public void setPolwithcheck(Object value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polwithcheck</code>.
     */
    public Object getPolwithcheck() {
        return (Object) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Long, String, Long[], Object, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Long, String, Long[], Object, Object> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PgPolicy.PG_POLICY.POLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgPolicy.PG_POLICY.POLRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgPolicy.PG_POLICY.POLCMD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field4() {
        return PgPolicy.PG_POLICY.POLROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return PgPolicy.PG_POLICY.POLQUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field6() {
        return PgPolicy.PG_POLICY.POLWITHCHECK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPolname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPolrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPolcmd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value4() {
        return getPolroles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return getPolqual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value6() {
        return getPolwithcheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value1(String value) {
        setPolname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value2(Long value) {
        setPolrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value3(String value) {
        setPolcmd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value4(Long[] value) {
        setPolroles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value5(Object value) {
        setPolqual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value6(Object value) {
        setPolwithcheck(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord values(String value1, Long value2, String value3, Long[] value4, Object value5, Object value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPolicyRecord
     */
    public PgPolicyRecord() {
        super(PgPolicy.PG_POLICY);
    }

    /**
     * Create a detached, initialised PgPolicyRecord
     */
    public PgPolicyRecord(String polname, Long polrelid, String polcmd, Long[] polroles, Object polqual, Object polwithcheck) {
        super(PgPolicy.PG_POLICY);

        set(0, polname);
        set(1, polrelid);
        set(2, polcmd);
        set(3, polroles);
        set(4, polqual);
        set(5, polwithcheck);
    }
}
