/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgPolicies;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPoliciesRecord extends TableRecordImpl<PgPoliciesRecord> implements Record7<String, String, String, String[], String, String, String> {

    private static final long serialVersionUID = 1547614625;

    /**
     * Setter for <code>pg_catalog.pg_policies.schemaname</code>.
     */
    public void setSchemaname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.schemaname</code>.
     */
    public String getSchemaname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_policies.tablename</code>.
     */
    public void setTablename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.tablename</code>.
     */
    public String getTablename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_policies.policyname</code>.
     */
    public void setPolicyname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.policyname</code>.
     */
    public String getPolicyname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_policies.roles</code>.
     */
    public void setRoles(String[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.roles</code>.
     */
    public String[] getRoles() {
        return (String[]) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_policies.cmd</code>.
     */
    public void setCmd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.cmd</code>.
     */
    public String getCmd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_policies.qual</code>.
     */
    public void setQual(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.qual</code>.
     */
    public String getQual() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_policies.with_check</code>.
     */
    public void setWithCheck(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policies.with_check</code>.
     */
    public String getWithCheck() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String[], String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String[], String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PgPolicies.PG_POLICIES.SCHEMANAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgPolicies.PG_POLICIES.TABLENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgPolicies.PG_POLICIES.POLICYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field4() {
        return PgPolicies.PG_POLICIES.ROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgPolicies.PG_POLICIES.CMD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgPolicies.PG_POLICIES.QUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PgPolicies.PG_POLICIES.WITH_CHECK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSchemaname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPolicyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value4() {
        return getRoles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCmd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getQual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWithCheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value1(String value) {
        setSchemaname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value2(String value) {
        setTablename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value3(String value) {
        setPolicyname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value4(String[] value) {
        setRoles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value5(String value) {
        setCmd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value6(String value) {
        setQual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord value7(String value) {
        setWithCheck(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPoliciesRecord values(String value1, String value2, String value3, String[] value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPoliciesRecord
     */
    public PgPoliciesRecord() {
        super(PgPolicies.PG_POLICIES);
    }

    /**
     * Create a detached, initialised PgPoliciesRecord
     */
    public PgPoliciesRecord(String schemaname, String tablename, String policyname, String[] roles, String cmd, String qual, String withCheck) {
        super(PgPolicies.PG_POLICIES);

        set(0, schemaname);
        set(1, tablename);
        set(2, policyname);
        set(3, roles);
        set(4, cmd);
        set(5, qual);
        set(6, withCheck);
    }
}
