/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgReplicationSlots;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgReplicationSlotsRecord extends TableRecordImpl<PgReplicationSlotsRecord> implements Record10<String, String, String, Long, String, Boolean, Integer, Long, Long, Object> {

    private static final long serialVersionUID = 525664763;

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.slot_name</code>.
     */
    public void setSlotName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.slot_name</code>.
     */
    public String getSlotName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.plugin</code>.
     */
    public void setPlugin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.plugin</code>.
     */
    public String getPlugin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.slot_type</code>.
     */
    public void setSlotType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.slot_type</code>.
     */
    public String getSlotType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.datoid</code>.
     */
    public void setDatoid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.datoid</code>.
     */
    public Long getDatoid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.database</code>.
     */
    public void setDatabase(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.database</code>.
     */
    public String getDatabase() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.active</code>.
     */
    public void setActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.active_pid</code>.
     */
    public void setActivePid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.active_pid</code>.
     */
    public Integer getActivePid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.xmin</code>.
     */
    public void setXmin(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.xmin</code>.
     */
    public Long getXmin() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.catalog_xmin</code>.
     */
    public void setCatalogXmin(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.catalog_xmin</code>.
     */
    public Long getCatalogXmin() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_replication_slots.restart_lsn</code>.
     */
    public void setRestartLsn(Object value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_replication_slots.restart_lsn</code>.
     */
    public Object getRestartLsn() {
        return (Object) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Long, String, Boolean, Integer, Long, Long, Object> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Long, String, Boolean, Integer, Long, Long, Object> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.SLOT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.PLUGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.SLOT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.DATOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.ACTIVE_PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.XMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.CATALOG_XMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field10() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.RESTART_LSN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSlotName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPlugin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSlotType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDatoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDatabase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getActivePid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getXmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCatalogXmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value10() {
        return getRestartLsn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value1(String value) {
        setSlotName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value2(String value) {
        setPlugin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value3(String value) {
        setSlotType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value4(Long value) {
        setDatoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value5(String value) {
        setDatabase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value6(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value7(Integer value) {
        setActivePid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value8(Long value) {
        setXmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value9(Long value) {
        setCatalogXmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord value10(Object value) {
        setRestartLsn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgReplicationSlotsRecord values(String value1, String value2, String value3, Long value4, String value5, Boolean value6, Integer value7, Long value8, Long value9, Object value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgReplicationSlotsRecord
     */
    public PgReplicationSlotsRecord() {
        super(PgReplicationSlots.PG_REPLICATION_SLOTS);
    }

    /**
     * Create a detached, initialised PgReplicationSlotsRecord
     */
    public PgReplicationSlotsRecord(String slotName, String plugin, String slotType, Long datoid, String database, Boolean active, Integer activePid, Long xmin, Long catalogXmin, Object restartLsn) {
        super(PgReplicationSlots.PG_REPLICATION_SLOTS);

        set(0, slotName);
        set(1, plugin);
        set(2, slotType);
        set(3, datoid);
        set(4, database);
        set(5, active);
        set(6, activePid);
        set(7, xmin);
        set(8, catalogXmin);
        set(9, restartLsn);
    }
}
