/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgStatActivity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatActivityRecord extends TableRecordImpl<PgStatActivityRecord> implements Record18<Long, String, Integer, Long, String, String, Object, String, Integer, Timestamp, Timestamp, Timestamp, Timestamp, Boolean, String, Long, Long, String> {

    private static final long serialVersionUID = 496858043;

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.datid</code>.
     */
    public void setDatid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.datid</code>.
     */
    public Long getDatid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.datname</code>.
     */
    public void setDatname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.datname</code>.
     */
    public String getDatname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.pid</code>.
     */
    public void setPid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.usesysid</code>.
     */
    public void setUsesysid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.usesysid</code>.
     */
    public Long getUsesysid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.usename</code>.
     */
    public void setUsename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.usename</code>.
     */
    public String getUsename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.application_name</code>.
     */
    public void setApplicationName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.application_name</code>.
     */
    public String getApplicationName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.client_addr</code>.
     */
    public void setClientAddr(Object value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.client_addr</code>.
     */
    public Object getClientAddr() {
        return (Object) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.client_hostname</code>.
     */
    public void setClientHostname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.client_hostname</code>.
     */
    public String getClientHostname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.client_port</code>.
     */
    public void setClientPort(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.client_port</code>.
     */
    public Integer getClientPort() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_start</code>.
     */
    public void setBackendStart(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_start</code>.
     */
    public Timestamp getBackendStart() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.xact_start</code>.
     */
    public void setXactStart(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.xact_start</code>.
     */
    public Timestamp getXactStart() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.query_start</code>.
     */
    public void setQueryStart(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.query_start</code>.
     */
    public Timestamp getQueryStart() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.state_change</code>.
     */
    public void setStateChange(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.state_change</code>.
     */
    public Timestamp getStateChange() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.waiting</code>.
     */
    public void setWaiting(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.waiting</code>.
     */
    public Boolean getWaiting() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.state</code>.
     */
    public void setState(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.state</code>.
     */
    public String getState() {
        return (String) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_xid</code>.
     */
    public void setBackendXid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_xid</code>.
     */
    public Long getBackendXid() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.backend_xmin</code>.
     */
    public void setBackendXmin(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.backend_xmin</code>.
     */
    public Long getBackendXmin() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_activity.query</code>.
     */
    public void setQuery(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_activity.query</code>.
     */
    public String getQuery() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, String, Integer, Long, String, String, Object, String, Integer, Timestamp, Timestamp, Timestamp, Timestamp, Boolean, String, Long, Long, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, String, Integer, Long, String, String, Object, String, Integer, Timestamp, Timestamp, Timestamp, Timestamp, Boolean, String, Long, Long, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgStatActivity.PG_STAT_ACTIVITY.DATID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgStatActivity.PG_STAT_ACTIVITY.DATNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PgStatActivity.PG_STAT_ACTIVITY.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgStatActivity.PG_STAT_ACTIVITY.USESYSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgStatActivity.PG_STAT_ACTIVITY.USENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgStatActivity.PG_STAT_ACTIVITY.APPLICATION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field7() {
        return PgStatActivity.PG_STAT_ACTIVITY.CLIENT_ADDR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PgStatActivity.PG_STAT_ACTIVITY.CLIENT_HOSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return PgStatActivity.PG_STAT_ACTIVITY.CLIENT_PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return PgStatActivity.PG_STAT_ACTIVITY.BACKEND_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return PgStatActivity.PG_STAT_ACTIVITY.XACT_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return PgStatActivity.PG_STAT_ACTIVITY.QUERY_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return PgStatActivity.PG_STAT_ACTIVITY.STATE_CHANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return PgStatActivity.PG_STAT_ACTIVITY.WAITING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return PgStatActivity.PG_STAT_ACTIVITY.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return PgStatActivity.PG_STAT_ACTIVITY.BACKEND_XID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return PgStatActivity.PG_STAT_ACTIVITY.BACKEND_XMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return PgStatActivity.PG_STAT_ACTIVITY.QUERY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getDatid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDatname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUsesysid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getApplicationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value7() {
        return getClientAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getClientHostname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getClientPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getBackendStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getXactStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getQueryStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getStateChange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getWaiting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getBackendXid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getBackendXmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getQuery();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value1(Long value) {
        setDatid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value2(String value) {
        setDatname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value3(Integer value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value4(Long value) {
        setUsesysid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value5(String value) {
        setUsename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value6(String value) {
        setApplicationName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value7(Object value) {
        setClientAddr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value8(String value) {
        setClientHostname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value9(Integer value) {
        setClientPort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value10(Timestamp value) {
        setBackendStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value11(Timestamp value) {
        setXactStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value12(Timestamp value) {
        setQueryStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value13(Timestamp value) {
        setStateChange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value14(Boolean value) {
        setWaiting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value15(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value16(Long value) {
        setBackendXid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value17(Long value) {
        setBackendXmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord value18(String value) {
        setQuery(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatActivityRecord values(Long value1, String value2, Integer value3, Long value4, String value5, String value6, Object value7, String value8, Integer value9, Timestamp value10, Timestamp value11, Timestamp value12, Timestamp value13, Boolean value14, String value15, Long value16, Long value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatActivityRecord
     */
    public PgStatActivityRecord() {
        super(PgStatActivity.PG_STAT_ACTIVITY);
    }

    /**
     * Create a detached, initialised PgStatActivityRecord
     */
    public PgStatActivityRecord(Long datid, String datname, Integer pid, Long usesysid, String usename, String applicationName, Object clientAddr, String clientHostname, Integer clientPort, Timestamp backendStart, Timestamp xactStart, Timestamp queryStart, Timestamp stateChange, Boolean waiting, String state, Long backendXid, Long backendXmin, String query) {
        super(PgStatActivity.PG_STAT_ACTIVITY);

        set(0, datid);
        set(1, datname);
        set(2, pid);
        set(3, usesysid);
        set(4, usename);
        set(5, applicationName);
        set(6, clientAddr);
        set(7, clientHostname);
        set(8, clientPort);
        set(9, backendStart);
        set(10, xactStart);
        set(11, queryStart);
        set(12, stateChange);
        set(13, waiting);
        set(14, state);
        set(15, backendXid);
        set(16, backendXmin);
        set(17, query);
    }
}
