/**
 * This class is generated by jOOQ
 */
package com.cf.pg_catalog.tables.records;


import com.cf.pg_catalog.tables.PgStatReplication;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatReplicationRecord extends TableRecordImpl<PgStatReplicationRecord> implements Record16<Integer, Long, String, String, Object, String, Integer, Timestamp, Long, String, Object, Object, Object, Object, Integer, String> {

    private static final long serialVersionUID = 120918285;

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.pid</code>.
     */
    public void setPid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.usesysid</code>.
     */
    public void setUsesysid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.usesysid</code>.
     */
    public Long getUsesysid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.usename</code>.
     */
    public void setUsename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.usename</code>.
     */
    public String getUsename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.application_name</code>.
     */
    public void setApplicationName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.application_name</code>.
     */
    public String getApplicationName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.client_addr</code>.
     */
    public void setClientAddr(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.client_addr</code>.
     */
    public Object getClientAddr() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.client_hostname</code>.
     */
    public void setClientHostname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.client_hostname</code>.
     */
    public String getClientHostname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.client_port</code>.
     */
    public void setClientPort(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.client_port</code>.
     */
    public Integer getClientPort() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.backend_start</code>.
     */
    public void setBackendStart(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.backend_start</code>.
     */
    public Timestamp getBackendStart() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.backend_xmin</code>.
     */
    public void setBackendXmin(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.backend_xmin</code>.
     */
    public Long getBackendXmin() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.state</code>.
     */
    public void setState(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.state</code>.
     */
    public String getState() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.sent_location</code>.
     */
    public void setSentLocation(Object value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.sent_location</code>.
     */
    public Object getSentLocation() {
        return (Object) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.write_location</code>.
     */
    public void setWriteLocation(Object value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.write_location</code>.
     */
    public Object getWriteLocation() {
        return (Object) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.flush_location</code>.
     */
    public void setFlushLocation(Object value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.flush_location</code>.
     */
    public Object getFlushLocation() {
        return (Object) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.replay_location</code>.
     */
    public void setReplayLocation(Object value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.replay_location</code>.
     */
    public Object getReplayLocation() {
        return (Object) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.sync_priority</code>.
     */
    public void setSyncPriority(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.sync_priority</code>.
     */
    public Integer getSyncPriority() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_replication.sync_state</code>.
     */
    public void setSyncState(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_replication.sync_state</code>.
     */
    public String getSyncState() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Long, String, String, Object, String, Integer, Timestamp, Long, String, Object, Object, Object, Object, Integer, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Long, String, String, Object, String, Integer, Timestamp, Long, String, Object, Object, Object, Object, Integer, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PgStatReplication.PG_STAT_REPLICATION.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgStatReplication.PG_STAT_REPLICATION.USESYSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgStatReplication.PG_STAT_REPLICATION.USENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgStatReplication.PG_STAT_REPLICATION.APPLICATION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return PgStatReplication.PG_STAT_REPLICATION.CLIENT_ADDR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgStatReplication.PG_STAT_REPLICATION.CLIENT_HOSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PgStatReplication.PG_STAT_REPLICATION.CLIENT_PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return PgStatReplication.PG_STAT_REPLICATION.BACKEND_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return PgStatReplication.PG_STAT_REPLICATION.BACKEND_XMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return PgStatReplication.PG_STAT_REPLICATION.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field11() {
        return PgStatReplication.PG_STAT_REPLICATION.SENT_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field12() {
        return PgStatReplication.PG_STAT_REPLICATION.WRITE_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field13() {
        return PgStatReplication.PG_STAT_REPLICATION.FLUSH_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field14() {
        return PgStatReplication.PG_STAT_REPLICATION.REPLAY_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return PgStatReplication.PG_STAT_REPLICATION.SYNC_PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return PgStatReplication.PG_STAT_REPLICATION.SYNC_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUsesysid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getApplicationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return getClientAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getClientHostname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getClientPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getBackendStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getBackendXmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value11() {
        return getSentLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value12() {
        return getWriteLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value13() {
        return getFlushLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value14() {
        return getReplayLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getSyncPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getSyncState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value1(Integer value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value2(Long value) {
        setUsesysid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value3(String value) {
        setUsename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value4(String value) {
        setApplicationName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value5(Object value) {
        setClientAddr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value6(String value) {
        setClientHostname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value7(Integer value) {
        setClientPort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value8(Timestamp value) {
        setBackendStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value9(Long value) {
        setBackendXmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value10(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value11(Object value) {
        setSentLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value12(Object value) {
        setWriteLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value13(Object value) {
        setFlushLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value14(Object value) {
        setReplayLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value15(Integer value) {
        setSyncPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord value16(String value) {
        setSyncState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatReplicationRecord values(Integer value1, Long value2, String value3, String value4, Object value5, String value6, Integer value7, Timestamp value8, Long value9, String value10, Object value11, Object value12, Object value13, Object value14, Integer value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatReplicationRecord
     */
    public PgStatReplicationRecord() {
        super(PgStatReplication.PG_STAT_REPLICATION);
    }

    /**
     * Create a detached, initialised PgStatReplicationRecord
     */
    public PgStatReplicationRecord(Integer pid, Long usesysid, String usename, String applicationName, Object clientAddr, String clientHostname, Integer clientPort, Timestamp backendStart, Long backendXmin, String state, Object sentLocation, Object writeLocation, Object flushLocation, Object replayLocation, Integer syncPriority, String syncState) {
        super(PgStatReplication.PG_STAT_REPLICATION);

        set(0, pid);
        set(1, usesysid);
        set(2, usename);
        set(3, applicationName);
        set(4, clientAddr);
        set(5, clientHostname);
        set(6, clientPort);
        set(7, backendStart);
        set(8, backendXmin);
        set(9, state);
        set(10, sentLocation);
        set(11, writeLocation);
        set(12, flushLocation);
        set(13, replayLocation);
        set(14, syncPriority);
        set(15, syncState);
    }
}
