/**
 * This class is generated by jOOQ
 */
package com.cf;


import com.cf.jooq.Jooq;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultCatalog extends CatalogImpl {

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();
    private static final long serialVersionUID = -428316942;

    /**
     * The schema <code>information_schema</code>.
     */
    /**
     * The schema <code>jooq</code>.
     */
    public final Jooq JOOQ = com.cf.jooq.Jooq.JOOQ;

    /**
     * The schema <code>library</code>.
     */

    /**
     * The schema <code>mysql</code>.
     */

    /**
     * The schema <code>performance_schema</code>.
     */

    /**
     * The schema <code>sys</code>.
     */

    /**
     * The schema <code>testdb</code>.
     */

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(

                Jooq.JOOQ
        );
    }
}
