/*
 * This file is generated by jOOQ.
*/
package com.cf.sys;


import com.cf.sys.tables.HostSummary;
import com.cf.sys.tables.HostSummaryByFileIo;
import com.cf.sys.tables.HostSummaryByFileIoType;
import com.cf.sys.tables.HostSummaryByStages;
import com.cf.sys.tables.HostSummaryByStatementLatency;
import com.cf.sys.tables.HostSummaryByStatementType;
import com.cf.sys.tables.InnodbBufferStatsBySchema;
import com.cf.sys.tables.InnodbBufferStatsByTable;
import com.cf.sys.tables.InnodbLockWaits;
import com.cf.sys.tables.IoByThreadByLatency;
import com.cf.sys.tables.IoGlobalByFileByBytes;
import com.cf.sys.tables.IoGlobalByFileByLatency;
import com.cf.sys.tables.IoGlobalByWaitByBytes;
import com.cf.sys.tables.IoGlobalByWaitByLatency;
import com.cf.sys.tables.LatestFileIo;
import com.cf.sys.tables.MemoryByHostByCurrentBytes;
import com.cf.sys.tables.MemoryByThreadByCurrentBytes;
import com.cf.sys.tables.MemoryByUserByCurrentBytes;
import com.cf.sys.tables.MemoryGlobalByCurrentBytes;
import com.cf.sys.tables.MemoryGlobalTotal;
import com.cf.sys.tables.Metrics;
import com.cf.sys.tables.Processlist;
import com.cf.sys.tables.PsCheckLostInstrumentation;
import com.cf.sys.tables.SchemaAutoIncrementColumns;
import com.cf.sys.tables.SchemaIndexStatistics;
import com.cf.sys.tables.SchemaObjectOverview;
import com.cf.sys.tables.SchemaRedundantIndexes;
import com.cf.sys.tables.SchemaTableLockWaits;
import com.cf.sys.tables.SchemaTableStatistics;
import com.cf.sys.tables.SchemaTableStatisticsWithBuffer;
import com.cf.sys.tables.SchemaTablesWithFullTableScans;
import com.cf.sys.tables.SchemaUnusedIndexes;
import com.cf.sys.tables.Session;
import com.cf.sys.tables.SessionSslStatus;
import com.cf.sys.tables.StatementAnalysis;
import com.cf.sys.tables.StatementsWithErrorsOrWarnings;
import com.cf.sys.tables.StatementsWithFullTableScans;
import com.cf.sys.tables.StatementsWithRuntimesIn_95thPercentile;
import com.cf.sys.tables.StatementsWithSorting;
import com.cf.sys.tables.StatementsWithTempTables;
import com.cf.sys.tables.SysConfig;
import com.cf.sys.tables.UserSummary;
import com.cf.sys.tables.UserSummaryByFileIo;
import com.cf.sys.tables.UserSummaryByFileIoType;
import com.cf.sys.tables.UserSummaryByStages;
import com.cf.sys.tables.UserSummaryByStatementLatency;
import com.cf.sys.tables.UserSummaryByStatementType;
import com.cf.sys.tables.Version;
import com.cf.sys.tables.WaitClassesGlobalByAvgLatency;
import com.cf.sys.tables.WaitClassesGlobalByLatency;
import com.cf.sys.tables.WaitsByHostByLatency;
import com.cf.sys.tables.WaitsByUserByLatency;
import com.cf.sys.tables.WaitsGlobalByLatency;
import com.cf.sys.tables.X$hostSummary;
import com.cf.sys.tables.X$hostSummaryByFileIo;
import com.cf.sys.tables.X$hostSummaryByFileIoType;
import com.cf.sys.tables.X$hostSummaryByStages;
import com.cf.sys.tables.X$hostSummaryByStatementLatency;
import com.cf.sys.tables.X$hostSummaryByStatementType;
import com.cf.sys.tables.X$innodbBufferStatsBySchema;
import com.cf.sys.tables.X$innodbBufferStatsByTable;
import com.cf.sys.tables.X$innodbLockWaits;
import com.cf.sys.tables.X$ioByThreadByLatency;
import com.cf.sys.tables.X$ioGlobalByFileByBytes;
import com.cf.sys.tables.X$ioGlobalByFileByLatency;
import com.cf.sys.tables.X$ioGlobalByWaitByBytes;
import com.cf.sys.tables.X$ioGlobalByWaitByLatency;
import com.cf.sys.tables.X$latestFileIo;
import com.cf.sys.tables.X$memoryByHostByCurrentBytes;
import com.cf.sys.tables.X$memoryByThreadByCurrentBytes;
import com.cf.sys.tables.X$memoryByUserByCurrentBytes;
import com.cf.sys.tables.X$memoryGlobalByCurrentBytes;
import com.cf.sys.tables.X$memoryGlobalTotal;
import com.cf.sys.tables.X$processlist;
import com.cf.sys.tables.X$psDigestAvgLatencyDistribution;
import com.cf.sys.tables.X$psDigest_95thPercentileByAvgUs;
import com.cf.sys.tables.X$psSchemaTableStatisticsIo;
import com.cf.sys.tables.X$schemaFlattenedKeys;
import com.cf.sys.tables.X$schemaIndexStatistics;
import com.cf.sys.tables.X$schemaTableLockWaits;
import com.cf.sys.tables.X$schemaTableStatistics;
import com.cf.sys.tables.X$schemaTableStatisticsWithBuffer;
import com.cf.sys.tables.X$schemaTablesWithFullTableScans;
import com.cf.sys.tables.X$session;
import com.cf.sys.tables.X$statementAnalysis;
import com.cf.sys.tables.X$statementsWithErrorsOrWarnings;
import com.cf.sys.tables.X$statementsWithFullTableScans;
import com.cf.sys.tables.X$statementsWithRuntimesIn_95thPercentile;
import com.cf.sys.tables.X$statementsWithSorting;
import com.cf.sys.tables.X$statementsWithTempTables;
import com.cf.sys.tables.X$userSummary;
import com.cf.sys.tables.X$userSummaryByFileIo;
import com.cf.sys.tables.X$userSummaryByFileIoType;
import com.cf.sys.tables.X$userSummaryByStages;
import com.cf.sys.tables.X$userSummaryByStatementLatency;
import com.cf.sys.tables.X$userSummaryByStatementType;
import com.cf.sys.tables.X$waitClassesGlobalByAvgLatency;
import com.cf.sys.tables.X$waitClassesGlobalByLatency;
import com.cf.sys.tables.X$waitsByHostByLatency;
import com.cf.sys.tables.X$waitsByUserByLatency;
import com.cf.sys.tables.X$waitsGlobalByLatency;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sys
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * VIEW
     */
    public static final HostSummary HOST_SUMMARY = com.cf.sys.tables.HostSummary.HOST_SUMMARY;

    /**
     * VIEW
     */
    public static final HostSummaryByFileIo HOST_SUMMARY_BY_FILE_IO = com.cf.sys.tables.HostSummaryByFileIo.HOST_SUMMARY_BY_FILE_IO;

    /**
     * VIEW
     */
    public static final HostSummaryByFileIoType HOST_SUMMARY_BY_FILE_IO_TYPE = com.cf.sys.tables.HostSummaryByFileIoType.HOST_SUMMARY_BY_FILE_IO_TYPE;

    /**
     * VIEW
     */
    public static final HostSummaryByStages HOST_SUMMARY_BY_STAGES = com.cf.sys.tables.HostSummaryByStages.HOST_SUMMARY_BY_STAGES;

    /**
     * VIEW
     */
    public static final HostSummaryByStatementLatency HOST_SUMMARY_BY_STATEMENT_LATENCY = com.cf.sys.tables.HostSummaryByStatementLatency.HOST_SUMMARY_BY_STATEMENT_LATENCY;

    /**
     * VIEW
     */
    public static final HostSummaryByStatementType HOST_SUMMARY_BY_STATEMENT_TYPE = com.cf.sys.tables.HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE;

    /**
     * VIEW
     */
    public static final InnodbBufferStatsBySchema INNODB_BUFFER_STATS_BY_SCHEMA = com.cf.sys.tables.InnodbBufferStatsBySchema.INNODB_BUFFER_STATS_BY_SCHEMA;

    /**
     * VIEW
     */
    public static final InnodbBufferStatsByTable INNODB_BUFFER_STATS_BY_TABLE = com.cf.sys.tables.InnodbBufferStatsByTable.INNODB_BUFFER_STATS_BY_TABLE;

    /**
     * VIEW
     */
    public static final InnodbLockWaits INNODB_LOCK_WAITS = com.cf.sys.tables.InnodbLockWaits.INNODB_LOCK_WAITS;

    /**
     * VIEW
     */
    public static final IoByThreadByLatency IO_BY_THREAD_BY_LATENCY = com.cf.sys.tables.IoByThreadByLatency.IO_BY_THREAD_BY_LATENCY;

    /**
     * VIEW
     */
    public static final IoGlobalByFileByBytes IO_GLOBAL_BY_FILE_BY_BYTES = com.cf.sys.tables.IoGlobalByFileByBytes.IO_GLOBAL_BY_FILE_BY_BYTES;

    /**
     * VIEW
     */
    public static final IoGlobalByFileByLatency IO_GLOBAL_BY_FILE_BY_LATENCY = com.cf.sys.tables.IoGlobalByFileByLatency.IO_GLOBAL_BY_FILE_BY_LATENCY;

    /**
     * VIEW
     */
    public static final IoGlobalByWaitByBytes IO_GLOBAL_BY_WAIT_BY_BYTES = com.cf.sys.tables.IoGlobalByWaitByBytes.IO_GLOBAL_BY_WAIT_BY_BYTES;

    /**
     * VIEW
     */
    public static final IoGlobalByWaitByLatency IO_GLOBAL_BY_WAIT_BY_LATENCY = com.cf.sys.tables.IoGlobalByWaitByLatency.IO_GLOBAL_BY_WAIT_BY_LATENCY;

    /**
     * VIEW
     */
    public static final LatestFileIo LATEST_FILE_IO = com.cf.sys.tables.LatestFileIo.LATEST_FILE_IO;

    /**
     * VIEW
     */
    public static final MemoryByHostByCurrentBytes MEMORY_BY_HOST_BY_CURRENT_BYTES = com.cf.sys.tables.MemoryByHostByCurrentBytes.MEMORY_BY_HOST_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final MemoryByThreadByCurrentBytes MEMORY_BY_THREAD_BY_CURRENT_BYTES = com.cf.sys.tables.MemoryByThreadByCurrentBytes.MEMORY_BY_THREAD_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final MemoryByUserByCurrentBytes MEMORY_BY_USER_BY_CURRENT_BYTES = com.cf.sys.tables.MemoryByUserByCurrentBytes.MEMORY_BY_USER_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final MemoryGlobalByCurrentBytes MEMORY_GLOBAL_BY_CURRENT_BYTES = com.cf.sys.tables.MemoryGlobalByCurrentBytes.MEMORY_GLOBAL_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final MemoryGlobalTotal MEMORY_GLOBAL_TOTAL = com.cf.sys.tables.MemoryGlobalTotal.MEMORY_GLOBAL_TOTAL;

    /**
     * VIEW
     */
    public static final Metrics METRICS = com.cf.sys.tables.Metrics.METRICS;

    /**
     * VIEW
     */
    public static final Processlist PROCESSLIST = com.cf.sys.tables.Processlist.PROCESSLIST;

    /**
     * VIEW
     */
    public static final PsCheckLostInstrumentation PS_CHECK_LOST_INSTRUMENTATION = com.cf.sys.tables.PsCheckLostInstrumentation.PS_CHECK_LOST_INSTRUMENTATION;

    /**
     * VIEW
     */
    public static final SchemaAutoIncrementColumns SCHEMA_AUTO_INCREMENT_COLUMNS = com.cf.sys.tables.SchemaAutoIncrementColumns.SCHEMA_AUTO_INCREMENT_COLUMNS;

    /**
     * VIEW
     */
    public static final SchemaIndexStatistics SCHEMA_INDEX_STATISTICS = com.cf.sys.tables.SchemaIndexStatistics.SCHEMA_INDEX_STATISTICS;

    /**
     * VIEW
     */
    public static final SchemaObjectOverview SCHEMA_OBJECT_OVERVIEW = com.cf.sys.tables.SchemaObjectOverview.SCHEMA_OBJECT_OVERVIEW;

    /**
     * VIEW
     */
    public static final SchemaRedundantIndexes SCHEMA_REDUNDANT_INDEXES = com.cf.sys.tables.SchemaRedundantIndexes.SCHEMA_REDUNDANT_INDEXES;

    /**
     * VIEW
     */
    public static final SchemaTablesWithFullTableScans SCHEMA_TABLES_WITH_FULL_TABLE_SCANS = com.cf.sys.tables.SchemaTablesWithFullTableScans.SCHEMA_TABLES_WITH_FULL_TABLE_SCANS;

    /**
     * VIEW
     */
    public static final SchemaTableLockWaits SCHEMA_TABLE_LOCK_WAITS = com.cf.sys.tables.SchemaTableLockWaits.SCHEMA_TABLE_LOCK_WAITS;

    /**
     * VIEW
     */
    public static final SchemaTableStatistics SCHEMA_TABLE_STATISTICS = com.cf.sys.tables.SchemaTableStatistics.SCHEMA_TABLE_STATISTICS;

    /**
     * VIEW
     */
    public static final SchemaTableStatisticsWithBuffer SCHEMA_TABLE_STATISTICS_WITH_BUFFER = com.cf.sys.tables.SchemaTableStatisticsWithBuffer.SCHEMA_TABLE_STATISTICS_WITH_BUFFER;

    /**
     * VIEW
     */
    public static final SchemaUnusedIndexes SCHEMA_UNUSED_INDEXES = com.cf.sys.tables.SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES;

    /**
     * VIEW
     */
    public static final Session SESSION = com.cf.sys.tables.Session.SESSION;

    /**
     * VIEW
     */
    public static final SessionSslStatus SESSION_SSL_STATUS = com.cf.sys.tables.SessionSslStatus.SESSION_SSL_STATUS;

    /**
     * VIEW
     */
    public static final StatementsWithErrorsOrWarnings STATEMENTS_WITH_ERRORS_OR_WARNINGS = com.cf.sys.tables.StatementsWithErrorsOrWarnings.STATEMENTS_WITH_ERRORS_OR_WARNINGS;

    /**
     * VIEW
     */
    public static final StatementsWithFullTableScans STATEMENTS_WITH_FULL_TABLE_SCANS = com.cf.sys.tables.StatementsWithFullTableScans.STATEMENTS_WITH_FULL_TABLE_SCANS;

    /**
     * VIEW
     */
    public static final StatementsWithRuntimesIn_95thPercentile STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE = com.cf.sys.tables.StatementsWithRuntimesIn_95thPercentile.STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE;

    /**
     * VIEW
     */
    public static final StatementsWithSorting STATEMENTS_WITH_SORTING = com.cf.sys.tables.StatementsWithSorting.STATEMENTS_WITH_SORTING;

    /**
     * VIEW
     */
    public static final StatementsWithTempTables STATEMENTS_WITH_TEMP_TABLES = com.cf.sys.tables.StatementsWithTempTables.STATEMENTS_WITH_TEMP_TABLES;

    /**
     * VIEW
     */
    public static final StatementAnalysis STATEMENT_ANALYSIS = com.cf.sys.tables.StatementAnalysis.STATEMENT_ANALYSIS;

    /**
     * The table <code>sys.sys_config</code>.
     */
    public static final SysConfig SYS_CONFIG = com.cf.sys.tables.SysConfig.SYS_CONFIG;

    /**
     * VIEW
     */
    public static final UserSummary USER_SUMMARY = com.cf.sys.tables.UserSummary.USER_SUMMARY;

    /**
     * VIEW
     */
    public static final UserSummaryByFileIo USER_SUMMARY_BY_FILE_IO = com.cf.sys.tables.UserSummaryByFileIo.USER_SUMMARY_BY_FILE_IO;

    /**
     * VIEW
     */
    public static final UserSummaryByFileIoType USER_SUMMARY_BY_FILE_IO_TYPE = com.cf.sys.tables.UserSummaryByFileIoType.USER_SUMMARY_BY_FILE_IO_TYPE;

    /**
     * VIEW
     */
    public static final UserSummaryByStages USER_SUMMARY_BY_STAGES = com.cf.sys.tables.UserSummaryByStages.USER_SUMMARY_BY_STAGES;

    /**
     * VIEW
     */
    public static final UserSummaryByStatementLatency USER_SUMMARY_BY_STATEMENT_LATENCY = com.cf.sys.tables.UserSummaryByStatementLatency.USER_SUMMARY_BY_STATEMENT_LATENCY;

    /**
     * VIEW
     */
    public static final UserSummaryByStatementType USER_SUMMARY_BY_STATEMENT_TYPE = com.cf.sys.tables.UserSummaryByStatementType.USER_SUMMARY_BY_STATEMENT_TYPE;

    /**
     * VIEW
     */
    public static final Version VERSION = com.cf.sys.tables.Version.VERSION;

    /**
     * VIEW
     */
    public static final WaitsByHostByLatency WAITS_BY_HOST_BY_LATENCY = com.cf.sys.tables.WaitsByHostByLatency.WAITS_BY_HOST_BY_LATENCY;

    /**
     * VIEW
     */
    public static final WaitsByUserByLatency WAITS_BY_USER_BY_LATENCY = com.cf.sys.tables.WaitsByUserByLatency.WAITS_BY_USER_BY_LATENCY;

    /**
     * VIEW
     */
    public static final WaitsGlobalByLatency WAITS_GLOBAL_BY_LATENCY = com.cf.sys.tables.WaitsGlobalByLatency.WAITS_GLOBAL_BY_LATENCY;

    /**
     * VIEW
     */
    public static final WaitClassesGlobalByAvgLatency WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY = com.cf.sys.tables.WaitClassesGlobalByAvgLatency.WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY;

    /**
     * VIEW
     */
    public static final WaitClassesGlobalByLatency WAIT_CLASSES_GLOBAL_BY_LATENCY = com.cf.sys.tables.WaitClassesGlobalByLatency.WAIT_CLASSES_GLOBAL_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$hostSummary X$HOST_SUMMARY = com.cf.sys.tables.X$hostSummary.X$HOST_SUMMARY;

    /**
     * VIEW
     */
    public static final X$hostSummaryByFileIo X$HOST_SUMMARY_BY_FILE_IO = com.cf.sys.tables.X$hostSummaryByFileIo.X$HOST_SUMMARY_BY_FILE_IO;

    /**
     * VIEW
     */
    public static final X$hostSummaryByFileIoType X$HOST_SUMMARY_BY_FILE_IO_TYPE = com.cf.sys.tables.X$hostSummaryByFileIoType.X$HOST_SUMMARY_BY_FILE_IO_TYPE;

    /**
     * VIEW
     */
    public static final X$hostSummaryByStages X$HOST_SUMMARY_BY_STAGES = com.cf.sys.tables.X$hostSummaryByStages.X$HOST_SUMMARY_BY_STAGES;

    /**
     * VIEW
     */
    public static final X$hostSummaryByStatementLatency X$HOST_SUMMARY_BY_STATEMENT_LATENCY = com.cf.sys.tables.X$hostSummaryByStatementLatency.X$HOST_SUMMARY_BY_STATEMENT_LATENCY;

    /**
     * VIEW
     */
    public static final X$hostSummaryByStatementType X$HOST_SUMMARY_BY_STATEMENT_TYPE = com.cf.sys.tables.X$hostSummaryByStatementType.X$HOST_SUMMARY_BY_STATEMENT_TYPE;

    /**
     * VIEW
     */
    public static final X$innodbBufferStatsBySchema X$INNODB_BUFFER_STATS_BY_SCHEMA = com.cf.sys.tables.X$innodbBufferStatsBySchema.X$INNODB_BUFFER_STATS_BY_SCHEMA;

    /**
     * VIEW
     */
    public static final X$innodbBufferStatsByTable X$INNODB_BUFFER_STATS_BY_TABLE = com.cf.sys.tables.X$innodbBufferStatsByTable.X$INNODB_BUFFER_STATS_BY_TABLE;

    /**
     * VIEW
     */
    public static final X$innodbLockWaits X$INNODB_LOCK_WAITS = com.cf.sys.tables.X$innodbLockWaits.X$INNODB_LOCK_WAITS;

    /**
     * VIEW
     */
    public static final X$ioByThreadByLatency X$IO_BY_THREAD_BY_LATENCY = com.cf.sys.tables.X$ioByThreadByLatency.X$IO_BY_THREAD_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$ioGlobalByFileByBytes X$IO_GLOBAL_BY_FILE_BY_BYTES = com.cf.sys.tables.X$ioGlobalByFileByBytes.X$IO_GLOBAL_BY_FILE_BY_BYTES;

    /**
     * VIEW
     */
    public static final X$ioGlobalByFileByLatency X$IO_GLOBAL_BY_FILE_BY_LATENCY = com.cf.sys.tables.X$ioGlobalByFileByLatency.X$IO_GLOBAL_BY_FILE_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$ioGlobalByWaitByBytes X$IO_GLOBAL_BY_WAIT_BY_BYTES = com.cf.sys.tables.X$ioGlobalByWaitByBytes.X$IO_GLOBAL_BY_WAIT_BY_BYTES;

    /**
     * VIEW
     */
    public static final X$ioGlobalByWaitByLatency X$IO_GLOBAL_BY_WAIT_BY_LATENCY = com.cf.sys.tables.X$ioGlobalByWaitByLatency.X$IO_GLOBAL_BY_WAIT_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$latestFileIo X$LATEST_FILE_IO = com.cf.sys.tables.X$latestFileIo.X$LATEST_FILE_IO;

    /**
     * VIEW
     */
    public static final X$memoryByHostByCurrentBytes X$MEMORY_BY_HOST_BY_CURRENT_BYTES = com.cf.sys.tables.X$memoryByHostByCurrentBytes.X$MEMORY_BY_HOST_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final X$memoryByThreadByCurrentBytes X$MEMORY_BY_THREAD_BY_CURRENT_BYTES = com.cf.sys.tables.X$memoryByThreadByCurrentBytes.X$MEMORY_BY_THREAD_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final X$memoryByUserByCurrentBytes X$MEMORY_BY_USER_BY_CURRENT_BYTES = com.cf.sys.tables.X$memoryByUserByCurrentBytes.X$MEMORY_BY_USER_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final X$memoryGlobalByCurrentBytes X$MEMORY_GLOBAL_BY_CURRENT_BYTES = com.cf.sys.tables.X$memoryGlobalByCurrentBytes.X$MEMORY_GLOBAL_BY_CURRENT_BYTES;

    /**
     * VIEW
     */
    public static final X$memoryGlobalTotal X$MEMORY_GLOBAL_TOTAL = com.cf.sys.tables.X$memoryGlobalTotal.X$MEMORY_GLOBAL_TOTAL;

    /**
     * VIEW
     */
    public static final X$processlist X$PROCESSLIST = com.cf.sys.tables.X$processlist.X$PROCESSLIST;

    /**
     * VIEW
     */
    public static final X$psDigest_95thPercentileByAvgUs X$PS_DIGEST_95TH_PERCENTILE_BY_AVG_US = com.cf.sys.tables.X$psDigest_95thPercentileByAvgUs.X$PS_DIGEST_95TH_PERCENTILE_BY_AVG_US;

    /**
     * VIEW
     */
    public static final X$psDigestAvgLatencyDistribution X$PS_DIGEST_AVG_LATENCY_DISTRIBUTION = com.cf.sys.tables.X$psDigestAvgLatencyDistribution.X$PS_DIGEST_AVG_LATENCY_DISTRIBUTION;

    /**
     * VIEW
     */
    public static final X$psSchemaTableStatisticsIo X$PS_SCHEMA_TABLE_STATISTICS_IO = com.cf.sys.tables.X$psSchemaTableStatisticsIo.X$PS_SCHEMA_TABLE_STATISTICS_IO;

    /**
     * VIEW
     */
    public static final X$schemaFlattenedKeys X$SCHEMA_FLATTENED_KEYS = com.cf.sys.tables.X$schemaFlattenedKeys.X$SCHEMA_FLATTENED_KEYS;

    /**
     * VIEW
     */
    public static final X$schemaIndexStatistics X$SCHEMA_INDEX_STATISTICS = com.cf.sys.tables.X$schemaIndexStatistics.X$SCHEMA_INDEX_STATISTICS;

    /**
     * VIEW
     */
    public static final X$schemaTablesWithFullTableScans X$SCHEMA_TABLES_WITH_FULL_TABLE_SCANS = com.cf.sys.tables.X$schemaTablesWithFullTableScans.X$SCHEMA_TABLES_WITH_FULL_TABLE_SCANS;

    /**
     * VIEW
     */
    public static final X$schemaTableLockWaits X$SCHEMA_TABLE_LOCK_WAITS = com.cf.sys.tables.X$schemaTableLockWaits.X$SCHEMA_TABLE_LOCK_WAITS;

    /**
     * VIEW
     */
    public static final X$schemaTableStatistics X$SCHEMA_TABLE_STATISTICS = com.cf.sys.tables.X$schemaTableStatistics.X$SCHEMA_TABLE_STATISTICS;

    /**
     * VIEW
     */
    public static final X$schemaTableStatisticsWithBuffer X$SCHEMA_TABLE_STATISTICS_WITH_BUFFER = com.cf.sys.tables.X$schemaTableStatisticsWithBuffer.X$SCHEMA_TABLE_STATISTICS_WITH_BUFFER;

    /**
     * VIEW
     */
    public static final X$session X$SESSION = com.cf.sys.tables.X$session.X$SESSION;

    /**
     * VIEW
     */
    public static final X$statementsWithErrorsOrWarnings X$STATEMENTS_WITH_ERRORS_OR_WARNINGS = com.cf.sys.tables.X$statementsWithErrorsOrWarnings.X$STATEMENTS_WITH_ERRORS_OR_WARNINGS;

    /**
     * VIEW
     */
    public static final X$statementsWithFullTableScans X$STATEMENTS_WITH_FULL_TABLE_SCANS = com.cf.sys.tables.X$statementsWithFullTableScans.X$STATEMENTS_WITH_FULL_TABLE_SCANS;

    /**
     * VIEW
     */
    public static final X$statementsWithRuntimesIn_95thPercentile X$STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE = com.cf.sys.tables.X$statementsWithRuntimesIn_95thPercentile.X$STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE;

    /**
     * VIEW
     */
    public static final X$statementsWithSorting X$STATEMENTS_WITH_SORTING = com.cf.sys.tables.X$statementsWithSorting.X$STATEMENTS_WITH_SORTING;

    /**
     * VIEW
     */
    public static final X$statementsWithTempTables X$STATEMENTS_WITH_TEMP_TABLES = com.cf.sys.tables.X$statementsWithTempTables.X$STATEMENTS_WITH_TEMP_TABLES;

    /**
     * VIEW
     */
    public static final X$statementAnalysis X$STATEMENT_ANALYSIS = com.cf.sys.tables.X$statementAnalysis.X$STATEMENT_ANALYSIS;

    /**
     * VIEW
     */
    public static final X$userSummary X$USER_SUMMARY = com.cf.sys.tables.X$userSummary.X$USER_SUMMARY;

    /**
     * VIEW
     */
    public static final X$userSummaryByFileIo X$USER_SUMMARY_BY_FILE_IO = com.cf.sys.tables.X$userSummaryByFileIo.X$USER_SUMMARY_BY_FILE_IO;

    /**
     * VIEW
     */
    public static final X$userSummaryByFileIoType X$USER_SUMMARY_BY_FILE_IO_TYPE = com.cf.sys.tables.X$userSummaryByFileIoType.X$USER_SUMMARY_BY_FILE_IO_TYPE;

    /**
     * VIEW
     */
    public static final X$userSummaryByStages X$USER_SUMMARY_BY_STAGES = com.cf.sys.tables.X$userSummaryByStages.X$USER_SUMMARY_BY_STAGES;

    /**
     * VIEW
     */
    public static final X$userSummaryByStatementLatency X$USER_SUMMARY_BY_STATEMENT_LATENCY = com.cf.sys.tables.X$userSummaryByStatementLatency.X$USER_SUMMARY_BY_STATEMENT_LATENCY;

    /**
     * VIEW
     */
    public static final X$userSummaryByStatementType X$USER_SUMMARY_BY_STATEMENT_TYPE = com.cf.sys.tables.X$userSummaryByStatementType.X$USER_SUMMARY_BY_STATEMENT_TYPE;

    /**
     * VIEW
     */
    public static final X$waitsByHostByLatency X$WAITS_BY_HOST_BY_LATENCY = com.cf.sys.tables.X$waitsByHostByLatency.X$WAITS_BY_HOST_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$waitsByUserByLatency X$WAITS_BY_USER_BY_LATENCY = com.cf.sys.tables.X$waitsByUserByLatency.X$WAITS_BY_USER_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$waitsGlobalByLatency X$WAITS_GLOBAL_BY_LATENCY = com.cf.sys.tables.X$waitsGlobalByLatency.X$WAITS_GLOBAL_BY_LATENCY;

    /**
     * VIEW
     */
    public static final X$waitClassesGlobalByAvgLatency X$WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY = com.cf.sys.tables.X$waitClassesGlobalByAvgLatency.X$WAIT_CLASSES_GLOBAL_BY_AVG_LATENCY;

    /**
     * VIEW
     */
    public static final X$waitClassesGlobalByLatency X$WAIT_CLASSES_GLOBAL_BY_LATENCY = com.cf.sys.tables.X$waitClassesGlobalByLatency.X$WAIT_CLASSES_GLOBAL_BY_LATENCY;
}
